general:
  model_name: release_intern_vit_classifier
  dataset_name: arm_malunion
  run_name: Training with attention pooling
  notes: ''
  custom_labels:
  - Malunion
  body_part: Arm
  treat_uncertain_as_positive: true
  perform_label_balancing: true
  compute_num_data_augmentations: true
  data_augmentation_target: 10000
  data_augmentation_min: 2000
  save_full_model: false
  unroll_images: false
paths:
  intern_vl_checkpoint_dir: /mnt/training/internvl_weights/internvl3_chimera_20250810_083849_1e-5_0810_no_label_gpt_bodypart/checkpoint-10466
  train_file: /mnt/training/splits/gradient_batches_1-5_segmed_batches_1-9_simonmed_batches_1-10_reports_with_labels_train.csv
  validation_file: /mnt/training/splits/gradient_batches_1-5_segmed_batches_1-9_simonmed_batches_1-10_reports_with_labels_val.csv
  test_file: /mnt/training/splits/gradient_batches_1-5_segmed_batches_1-9_simonmed_batches_1-10_reports_with_labels_test.csv
  base_path_substitutions:
    gradient/22JUL2024: /mnt/all-data/sfs-gradient-chest/22JUL2024
    gradient/20DEC2024: /mnt/all-data/sfs-gradient-chest/20DEC2024
    gradient/09JAN2025: /mnt/all-data/sfs-gradient-chest/09JAN2025
    gradient/16AUG2024: /mnt/all-data/sfs-gradient-nochest/16AUG2024
    gradient/13JAN2025: /mnt/all-data/sfs-gradient-nochest/13JAN2025/deid
    segmed/batch1: /mnt/all-data/sfs-segmed-1
    segmed/batch2: /mnt/all-data/sfs-segmed-2
    segmed/batch3: /mnt/all-data/sfs-segmed-34/segmed_3
    segmed/batch4: /mnt/all-data/sfs-segmed-34/segmed_4
    segmed/batch5: /mnt/all-data/sfs-segmed567/segmed_5
    segmed/batch6: /mnt/all-data/sfs-segmed567/segmed_6
    segmed/batch7: /mnt/all-data/sfs-segmed567/segmed_7
    segmed/batch8: /mnt/all-data/sfs-segmed89/batch8
    segmed/batch9: /mnt/all-data/sfs-segmed89/batch9
    simonmed: /mnt/all-data/sfs-simonmed
  output_dir: /mnt/training/checkpoints
training:
  perform_intra_epoch_validation: true
  intra_epoch_validation_step: 3000
  send_wandb_notification: false
  device: cuda
  device_ids: None
  num_training_workers_per_gpu: 32
  num_validation_workers_per_gpu: 32
  learning_rate: 0.01
  warmup_ratio: 0.05
  num_epochs: 2
  training_batch_size: 128
  validation_batch_size: 32
  min_allowed_batch_size: 2
  multi_image_input: true
  max_multi_images: 8
  use_attentional_pooling: true
