
GRADIENT_GCS_BUCKET_NAME = "epsilon-data-us-central1"
GRADIENT_GCS_REPORTS_FILE = "GRADIENT-DATABASE/REPORTS/CR/us-data-cr-23july2024.csv"
GRADIENT_GCS_IMAGES_DIR = "GRADIENT-DATABASE/CR/22JUL2024"

EPSILON_GCS_BUCKET_NAME = "gradient-crs"
EPSILON_GCS_IMAGES_DIR = "22JUL2024"

OUT_FILE_NAME ="us-data-cr-23july2024-image_to_report_mapping.csv"
