
GRADIENT_GCS_BUCKET_NAME = "epsilon-data-us-central1"
GRADIENT_GCS_REPORTS_FILE = "GRADIENT-DATABASE/REPORTS/CR/cr-16ago2024.csv"
GRADIENT_GCS_IMAGES_DIR = "GRADIENT-DATABASE/CR/16AG02924"

EPSILON_GCS_BUCKET_NAME = "gradient-crs"
EPSILON_GCS_IMAGES_DIR = "16AG02924"

OUT_FILE_NAME ="cr-16ago2024-image_to_report_mapping.csv"
