"""Label maps for v1.3.0"""

# Defined:
# - FINEGRAINED_LABELS_BY_BODY_PART
# - CONSOLIDATED_LABELS_BY_BODY_PART
# - FINEGRAINED_TO_CONSOLIDATED_BY_BODY_PART
# - CONSOLIDATED_TO_FINEGRAINED_BY_BODY_PART


FINEGRAINED_LABELS_BY_BODY_PART = {
    "Abdomen": [
        "Bowel obstruction",
        "Bowel dilation",
        "Colonic distension",
        "Air fluid levels",
        "Pneumoperitoneum",
        "Free air",
        "Calcifications",
        "Vascular calcifications in abdominal vessels",
        "Calcified phleboliths",
        "Heterotopic ossification",
        "Abnormal calcifications",
        "Foreign bodies",
        "Organomegaly",
        "Masses",
        "Ileus",
        "Abnormal gas patterns",
        "Ascites",
        "Stool",
        "Constipation",
        "Support devices",
        "Pneumatosis intestinalis",
        "Portal venous gas",
        "Gallstones",
        "Renal stones",
        "Ureteral calculi",
        "Medical devices",
        "Ureteral stents",
        "Surgical clips or staples",
        "Iud",
        "Uterine fibroids",
        "Degenerative changes",
        "Pneumatosis",
        "Bowel wall thickening",
        "Diaphragmatic hernia",
        "Bladder distension or masses",
        "No findings",
    ],
    "Arm": [
        "Fracture",
        "Scaphoid fracture",
        "Buckle fracture",
        "Bony bankart",
        "Hill sachs",
        "Dislocation",
        "Joint subluxation",
        "Acromioclavicular joint separation",
        "Ac separation",
        "Joint effusion",
        "Soft tissue swelling",
        "Subcutaneous gas",
        "Foreign bodies",
        "Bone lesions",
        "Osteomyelitis",
        "Periosteal reaction",
        "Edema",
        "Erosive change",
        "Rarefaction",
        "Osseous destruction",
        "Bony mineralization",
        "Amputation",
        "Growth plate abnormalities",
        "Hardware complication",
        "Malunion",
        "Nonunion",
        "Tendinous calcifications",
        "Charcot joint",
        "Synostosis",
        "Degenerative changes",
        "Enthesophytes",
        "Osteophytes",
        "Arthritic changes",
        "Joint space narrowing",
        "Ulnar variance",
        "Soft tissue calcifications",
        "Myositis ossificans",
        "Synostosis between radius and ulna",
        "Bone infarcts",
        "Fat pad signs suggesting joint effusion",
        "Os subcoronoideum",
        "Os supratrochlear",
        "Os acromiale",
        "Rotator cuff calcific tendinitis",
        "Distal clavicle osteolysis",
        "No findings",
    ],
    "C-spine": [
        "Foreign body",
        "Foreign bodies",
        "Fracture",
        "Vertebral height loss",
        "Compression fracture",
        "Vertebral collapse",
        "Odontoid fracture",
        "Hyoid bone fractures or dislocations",
        "Thyroid cartilage fractures",
        "Laryngeal fracture",
        "Degenerative changes",
        "Osteophytes",
        "Intervertebral disc narrowing",
        "Vacuum disc phenomenon",
        "Spondylosis",
        "Facet joint arthropathy",
        "Spinal canal narrowing",
        "Enthesophytes",
        "Uncovertebral joint arthrosis",
        "Neural foraminal narrowing",
        "Dislocation",
        "Traumatic subluxation",
        "Atlantoaxial subluxation",
        "Atlanto-occipital joint abnormalities",
        "Spondylolisthesis",
        "Listhesis",
        "Scoliosis",
        "Spondylolysis",
        "Bone lesions",
        "Osteomyelitis",
        "Bony mineralization",
        "Support devices",
        "Tracheostomy tube placement abnormalities",
        "Hardware",
        "Hardware malposition",
        "Hardware loosening",
        "Postoperative fusion changes",
        "Spinal deformity",
        "Pseudoarticulation",
        "Schmorls node",
        "Ankylosis",
        "Congenital fusion of cervical vertebrae (klippel-feil syndrome)",
        "Odontoid process sclerosis",
        "Odontoid process fragmentation",
        "Bilateral or unilateral facet joint ankylosis",
        "Tracheal stenosis",
        "Tracheal deviation",
        "Soft tissue swelling",
        "Epiglottitis",
        "Airway patency/narrowing",
        "Prevertebral soft tissue widening",
        "Subglottic narrowing",
        "Prevertebral hematoma",
        "Pharyngeal soft tissue masses",
        "Cervical rib",
        "Cervical rib variations",
        "Soft tissue emphysema",
        "Retropharyngeal air",
        "Post-surgical air",
        "Soft tissue air tracking from perforation",
        "Calcifications",
        "Aortic calcifications",
        "Carotid calcifications",
        "Ossification of the posterior longitudinal ligament",
        "Calcific tendinitis of the longus colli muscle",
        "Aortic calcifications",
        "Cervical spine alignment",
        "Kyphosis",
        "Lordosis",
        "Lateral curvature",
        "Straightening",
        "Hyoid bone abnormality",
        "Thyroid enlargement",
        "Esophageal dilation",
        "No findings",
    ],
    "Chest": [
        "Adenopathy",
        "Airspace opacity",
        "Consolidation",
        "Pneumonia",
        "Covid-19",
        "Pneumonitis",
        "Aortic enlargement",
        "Degenerative changes",
        "Arthritis",
        "Asthma",
        "Atelectasis",
        "Bronchitis",
        "Calcification",
        "Cardiomegaly",
        "Pericardial effusion",
        "Pulmonary contusion",
        "Congestive heart failure",
        "Pulmonary edema",
        "Kerley b lines",
        "Venous congestion",
        "Edema",
        "Air bronchogram",
        "Emphysema",
        "Hyperinflation",
        "Enlarged mediastinum",
        "Enlarged pulmonary artery",
        "Fibrosis",
        "Fracture",
        "Rib fracture",
        "Granuloma",
        "Calcified granuloma",
        "Hiatal hernia",
        "Hernia",
        "Pulmonary cavitary lesion",
        "Mass/nodule",
        "Mediastinal shift",
        "Osteoporosis",
        "Perihilar opacity",
        "Pleural effusion",
        "Costophrenic angle blunting",
        "Opacified hemithorax",
        "Pleural thickening",
        "Pneumothorax",
        "Lucent hemithorax",
        "Diaphragmatic elevation",
        "Diaphragmatic eventration",
        "Diaphragmatic paralysis",
        "Flattening of the hemi diaphragm",
        "Sarcoidosis",
        "Scarring",
        "Tortuous aorta",
        "Tuberculosis",
        "Pleural plaque",
        "Foreign bodies",
        "Support devices",
        "Endotracheal tube malposition",
        "Nasogastric tube malposition",
        "Tracheostomy tube malposition",
        "Enteric tube",
        "Cardiac devices",
        "Pacemaker leads",
        "Interstitial lung disease (ild)",
        "Bronchiectasis",
        "Subcutaneous emphysema",
        "Lung volume loss",
        "Bone lesion",
        "Lytic lesions",
        "Blastic lesions",
        "Spondlyitis",
        "Scoliosis",
        "Chest wall mass",
        "Tracheal deviation",
        "Post-surgical changes",
        "Tracheal stenosis",
        "Esophageal dilation",
        "Pneumomediastinum",
        "Pneumoperitoneum",
        "Cervical ribs",
        "Distended bowel",
        "No findings",
    ],
    "Foot": [
        "Fracture",
        "Malunion",
        "Osteochondral lesion",
        "Stress fracture",
        "Avulsion fractures",
        "Dislocation",
        "Joint subluxation",
        "Lisfranc",
        "Claw toe",
        "Hammer toe",
        "Arthritic changes",
        "Joint effusion",
        "Soft tissue swelling",
        "Edema",
        "Subcutaneous gas",
        "Foreign bodies",
        "Bone lesions",
        "Osteomyelitis",
        "Periosteal reaction",
        "Degenerative changes",
        "Joint space narrowing",
        "Subchondral cysts",
        "Erosive change",
        "Osseous destruction",
        "Bony mineralization",
        "Charcot joint",
        "Amputation",
        "Tarsal coalition",
        "Growth plate abnormalities",
        "Hardware complication",
        "Syndesmotic injury",
        "Kagers fat pad",
        "Nonunion",
        "Tendinous calcifications",
        "Hallux valgus",
        "Synostosis",
        "Soft tissue calcifications",
        "Ossicles",
        "Accessory ossicles",
        "Os navicularis",
        "Os trigonum",
        "Os interphalangeus",
        "Rarefaction",
        "No findings",
    ],
    "Hand": [
        "Fracture",
        "Tuft fractures",
        "Buckle fracture",
        "Scaphoid fracture",
        "Tendon avulsion fractures",
        "Dislocation",
        "Joint subluxation",
        "Lunate dislocation",
        "Perilunate dislocation",
        "Soft tissue swelling",
        "Subcutaneous gas",
        "Foreign bodies",
        "Bone lesions",
        "Osteomyelitis",
        "Periosteal reaction",
        "Erosive change",
        "Rarefaction",
        "Osseous destruction",
        "Phalangeal osteolysis",
        "Bony mineralization",
        "Amputation",
        "Hardware",
        "Hardware complication",
        "Malunion",
        "Nonunion",
        "Tendinous calcifications",
        "Soft tissue calcifications",
        "Charcot joint",
        "Synostosis",
        "Degenerative changes",
        "Enthesophytes",
        "Osteophytes",
        "Arthritic changes",
        "Joint space narrowing",
        "Ulnar variance",
        "Ossicles",
        "Os interphalangeus",
        "Edema",
        "Boutonniere deformity",
        "Swan neck deformity",
        "Trigger finger deformity signs",
        "Madelung deformity",
        "Carpal coalition",
        "Avascular necrosis",
        "Acro-osteolysis",
        "Carpal boss",
        "Enostosis",
        "Scaphoid avascular necrosis (kienbocks disease)",
        "No findings",
    ],
    "Head": [
        "Fracture",
        "Pathological fracture",
        "Nonunion",
        "Malunion",
        "Dislocation",
        "Joint subluxation",
        "Soft tissue swelling",
        "Orbital emphysema",
        "Subcutaneous gas",
        "Foreign bodies",
        "Metallic foreign body",
        "Intracranial foreign body",
        "Dental artifacts",
        "Periosteal reaction",
        "Osteomyelitis",
        "Erosive change",
        "Bony mineralization",
        "Support devices",
        "Hardware complication",
        "Shunt tubing or valves",
        "Degenerative changes",
        "Arthritic changes",
        "Joint space narrowing",
        "Pneumocephalus",
        "Calvarial lesions",
        "Aplastic",
        "Aplasia",
        "Osseous destruction",
        "Bone lesions",
        "Skull base asymmetry",
        "Sutural diastasis",
        "Hypoplastic sinus",
        "Paranasal sinus expansion",
        "Soft tissue calcifications",
        "Abnormal calcifications",
        "Sinusitis",
        "Air-fluid levels",
        "Mucosal thickening",
        "Mastoid opacity",
        "Middle ear effusion",
        "Post-surgical changes",
        "Craniotomy",
        "Rarefaction",
        "No findings",
    ],
    "L-spine": [
        "Fracture",
        "Vertebral height loss",
        "Compression fracture",
        "Vertebral collapse",
        "Degenerative changes",
        "Osteophytes",
        "Intervertebral disc narrowing",
        "Vacuum disc phenomenon",
        "Spondylosis",
        "Facet joint arthropathy",
        "Spinal canal narrowing",
        "Enthesophytes",
        "Spondylolisthesis",
        "Scoliosis",
        "Lateral curvature",
        "Scoliosis with rotational deformities",
        "Hardware",
        "Hardware malposition",
        "Hardware loosening",
        "Postoperative fusion changes",
        "Support devices",
        "Bone lesions",
        "Osteomyelitis",
        "Bony mineralization",
        "Sacroiliitis",
        "Spinal deformity",
        "Pseudoarticulation",
        "Schmorls node",
        "Ankylosis",
        "Spina bifida occulta",
        "Sacralization of l5",
        "Lumbarization of s1",
        "Transitional vertebrae",
        "Transitional sacral vertebrae anomalies",
        "Pars interarticularis defects",
        "Spondylolysis",
        "Calcification",
        "Aortic calcifications",
        "Ossification of the posterior longitudinal ligament",
        "Iliolumbar ligament calcifications or ossifications",
        "Calcification of interspinous ligaments",
        "Straightening",
        "Kyphosis",
        "Lordosis",
        "No findings",
    ],
    "Leg": [
        "Fracture",
        "Stress reaction",
        "Malunion",
        "Nonunion",
        "Stress fracture callus formation",
        "Dislocation",
        "Joint subluxation",
        "Degenerative changes",
        "Enthesophytes",
        "Osteophytes",
        "Subchondral cyst",
        "Arthritic changes",
        "Osteochondral defects",
        "Joint space narrowing",
        "Joint effusion",
        "Soft tissue swelling",
        "Edema",
        "Subcutaneous gas",
        "Foreign bodies",
        "Bone lesions",
        "Osteomyelitis",
        "Periosteal reaction",
        "Erosive change",
        "Rarefaction",
        "Osseous destruction",
        "Bony mineralization",
        "Hardware",
        "Hardware complication",
        "Loosening of hardware",
        "Migration of hardware",
        "Amputation",
        "Growth plate abnormalities",
        "Tendinous calcifications",
        "Soft tissue calcifications",
        "Charcot joint",
        "Limb-length discrepancy",
        "Synostosis",
        "Femoral acetabular impingement",
        "Fai",
        "Cam deformity",
        "Cortical thickening",
        "Bone infarcts",
        "Heterotopic ossification",
        "Myositis ossificans",
        "Calcifications",
        "Meniscal calcifications",
        "Patellar tracking abnormalities",
        "Bipartite patella",
        "Osteochondritis dissecans",
        "Intraarticular bodies",
        "Osteochondral lesions",
        "No findings",
    ],
    "Pelvis": [
        "Fracture",
        "Dislocation",
        "Joint widening",
        "Pubic symphysis diastasis",
        "Bone lesions",
        "Avascular necrosis",
        "Soft tissue swelling",
        "Subcutaneous gas",
        "Osteomyelitis",
        "Bony mineralization",
        "Medical devices",
        "Urologic stent",
        "Foley catheter",
        "Iud",
        "Soft tissue mass",
        "Intra-articular body",
        "Ureteral calculi",
        "Degenerative changes",
        "Enthesopathy",
        "Arthritis",
        "Subchondral cyst",
        "Sacralization of spine",
        "Stool",
        "Constipation",
        "Cam deformity",
        "Slipped capital femoral epiphysis",
        "Femoral acetabular impingement",
        "Protrusio acetabuli",
        "Osteochondral defects",
        "Heterotopic ossification",
        "Soft tissue calcifications",
        "Acetabular retroversion sign",
        "Crossover sign",
        "Sacroiliitis",
        "Osteitis condensans ilii",
        "Osteitis pubis",
        "Pelvic vascular calcifications",
        "Pelvic phleboliths",
        "No findings",
    ],
    "T-spine": [
        "Fracture",
        "Vertebral height loss",
        "Compression fracture",
        "Vertebral collapse",
        "Rib head fractures or dislocations",
        "Degenerative changes",
        "Osteophytes",
        "Intervertebral disc narrowing",
        "Vacuum disc phenomenon",
        "Spondylosis",
        "Facet joint arthropathy",
        "Spinal canal narrowing",
        "Enthesophytes",
        "Costovertebral joint arthropathy",
        "Spondylolisthesis",
        "Bone lesions",
        "Absent pedicle",
        "Osteomyelitis",
        "Spondylolysis",
        "Bony mineralization",
        "Support devices",
        "Straightening",
        "Kyphosis",
        "Lordosis",
        "Spinal deformity",
        "Pseudoarticulation",
        "Schmorls node",
        "Ankylosis",
        "Spina bifida occulta",
        "Butterfly vertebra",
        "Hemivertebra",
        "Block vertebrae",
        "Pars interarticularis defects",
        "Spondylolysis",
        "Hardware",
        "Hardware malposition",
        "Hardware loosening",
        "Postoperative fusion changes",
        "Scoliosis",
        "Lateral curvature",
        "Scoliosis with rotational deformities",
        "Levoconvex",
        "Dextroconvex",
        "Calcification",
        "Aortic calcifications",
        "Ossification of the posterior longitudinal ligament",
        "Calcification of interspinous ligaments",
        "Ossification of the ligamentum flavum",
        "Rib notching",
        "Costotransverse joint abnormalities",
        "No findings",
    ],
}


CONSOLIDATED_LABELS_BY_BODY_PART = {
    "Abdomen": [
        "Bowel obstruction",
        "Pneumoperitoneum",
        "Calcifications",
        "Foreign bodies",
        "Organomegaly",
        "Masses",
        "Ileus",
        "Ascites",
        "Stool",
        "Support devices",
        "Pneumatosis intestinalis",
        "Portal venous gas",
        "Gallstones",
        "Renal stones",
        "Ureteral calculi",
        "Medical devices",
        "Iud",
        "Uterine fibroids",
        "Degenerative changes",
        "Pneumatosis",
        "Bowel wall thickening",
        "Diaphragmatic hernia",
        "Bladder distension or masses",
        "No findings",
    ],
    "Arm": [
        "Fracture",
        "Dislocation",
        "Joint effusion",
        "Soft tissue swelling",
        "Subcutaneous gas",
        "Foreign bodies",
        "Bone lesions",
        "Osteomyelitis",
        "Erosive change",
        "Bony mineralization",
        "Amputation",
        "Growth plate abnormalities",
        "Hardware complication",
        "Malunion",
        "Tendinous calcifications",
        "Charcot joint",
        "Synostosis",
        "Degenerative changes",
        "Ulnar variance",
        "Soft tissue calcifications",
        "Synostosis between radius and ulna",
        "Bone infarcts",
        "Fat pad signs suggesting joint effusion",
        "Os subcoronoideum",
        "Rotator cuff calcific tendinitis",
        "Distal clavicle osteolysis",
        "No findings",
    ],
    "C-spine": [
        "Foreign body",
        "Fracture",
        "Degenerative changes",
        "Dislocation",
        "Spondylolisthesis",
        "Scoliosis",
        "Spondylolysis",
        "Bone lesions",
        "Osteomyelitis",
        "Bony mineralization",
        "Support devices",
        "Hardware",
        "Spinal deformity",
        "Tracheal stenosis",
        "Soft tissue swelling",
        "Cervical rib",
        "Soft tissue emphysema",
        "Calcifications",
        "Aortic calcifications",
        "Cervical spine alignment",
        "Hyoid bone abnormality",
        "Thyroid enlargement",
        "Esophageal dilation",
        "No findings",
    ],
    "Chest": [
        "Adenopathy",
        "Airspace opacity",
        "Aortic enlargement",
        "Degenerative changes",
        "Asthma",
        "Atelectasis",
        "Bronchitis",
        "Calcification",
        "Cardiomegaly",
        "Pulmonary contusion",
        "Congestive heart failure",
        "Air bronchogram",
        "Emphysema",
        "Enlarged mediastinum",
        "Enlarged pulmonary artery",
        "Fibrosis",
        "Fracture",
        "Granuloma",
        "Hiatal hernia",
        "Pulmonary cavitary lesion",
        "Mass/nodule",
        "Mediastinal shift",
        "Osteoporosis",
        "Perihilar opacity",
        "Pleural effusion",
        "Pleural thickening",
        "Pneumothorax",
        "Diaphragmatic elevation",
        "Sarcoidosis",
        "Scarring",
        "Tortuous aorta",
        "Tuberculosis",
        "Pleural plaque",
        "Foreign bodies",
        "Support devices",
        "Cardiac devices",
        "Interstitial lung disease (ild)",
        "Bronchiectasis",
        "Subcutaneous emphysema",
        "Lung volume loss",
        "Bone lesion",
        "Scoliosis",
        "Chest wall mass",
        "Tracheal deviation",
        "Post-surgical changes",
        "Tracheal stenosis",
        "Esophageal dilation",
        "Pneumomediastinum",
        "Pneumoperitoneum",
        "Cervical ribs",
        "Distended bowel",
        "No findings",
    ],
    "Foot": [
        "Fracture",
        "Dislocation",
        "Arthritic changes",
        "Joint effusion",
        "Soft tissue swelling",
        "Subcutaneous gas",
        "Foreign bodies",
        "Bone lesions",
        "Osteomyelitis",
        "Degenerative changes",
        "Erosive change",
        "Bony mineralization",
        "Charcot joint",
        "Amputation",
        "Tarsal coalition",
        "Growth plate abnormalities",
        "Hardware complication",
        "Syndesmotic injury",
        "Kagers fat pad",
        "Tendinous calcifications",
        "Hallux valgus",
        "Synostosis",
        "Soft tissue calcifications",
        "Ossicles",
        "Rarefaction",
        "No findings",
    ],
    "Hand": [
        "Fracture",
        "Dislocation",
        "Soft tissue swelling",
        "Foreign bodies",
        "Bone lesions",
        "Osteomyelitis",
        "Erosive change",
        "Bony mineralization",
        "Amputation",
        "Hardware",
        "Malunion",
        "Tendinous calcifications",
        "Charcot joint",
        "Synostosis",
        "Degenerative changes",
        "Ulnar variance",
        "Ossicles",
        "Edema",
        "Boutonniere deformity",
        "Carpal coalition",
        "Avascular necrosis",
        "Acro-osteolysis",
        "Carpal boss",
        "Enostosis",
        "Scaphoid avascular necrosis (kienbocks disease)",
        "No findings",
    ],
    "Head": [
        "Fracture",
        "Dislocation",
        "Soft tissue swelling",
        "Orbital emphysema",
        "Foreign bodies",
        "Periosteal reaction",
        "Erosive change",
        "Bony mineralization",
        "Support devices",
        "Degenerative changes",
        "Pneumocephalus",
        "Calvarial lesions",
        "Soft tissue calcifications",
        "Sinusitis",
        "Mastoid opacity",
        "Post-surgical changes",
        "Rarefaction",
        "No findings",
    ],
    "L-spine": [
        "Fracture",
        "Degenerative changes",
        "Spondylolisthesis",
        "Scoliosis",
        "Hardware",
        "Support devices",
        "Bone lesions",
        "Osteomyelitis",
        "Bony mineralization",
        "Sacroiliitis",
        "Spinal deformity",
        "Calcification",
        "Straightening",
        "No findings",
    ],
    "Leg": [
        "Fracture",
        "Dislocation",
        "Degenerative changes",
        "Joint effusion",
        "Soft tissue swelling",
        "Subcutaneous gas",
        "Foreign bodies",
        "Bone lesions",
        "Osteomyelitis",
        "Erosive change",
        "Bony mineralization",
        "Hardware",
        "Amputation",
        "Growth plate abnormalities",
        "Tendinous calcifications",
        "Charcot joint",
        "Limb-length discrepancy",
        "Synostosis",
        "Femoral acetabular impingement",
        "Cortical thickening",
        "Bone infarcts",
        "Heterotopic ossification",
        "Calcifications",
        "Patellar tracking abnormalities",
        "Bipartite patella",
        "Osteochondritis dissecans",
        "Intraarticular bodies",
        "Osteochondral lesions",
        "No findings",
    ],
    "Pelvis": [
        "Fracture",
        "Dislocation",
        "Bone lesions",
        "Avascular necrosis",
        "Soft tissue swelling",
        "Subcutaneous gas",
        "Osteomyelitis",
        "Bony mineralization",
        "Medical devices",
        "Iud",
        "Soft tissue mass",
        "Intra-articular body",
        "Ureteral calculi",
        "Degenerative changes",
        "Sacralization of spine",
        "Stool",
        "Cam deformity",
        "Slipped capital femoral epiphysis",
        "Femoral acetabular impingement",
        "Protrusio acetabuli",
        "Osteochondral defects",
        "Heterotopic ossification",
        "Acetabular retroversion sign",
        "Crossover sign",
        "Sacroiliitis",
        "Osteitis condensans ilii",
        "Osteitis pubis",
        "Pelvic vascular calcifications",
        "No findings",
    ],
    "T-spine": [
        "Fracture",
        "Degenerative changes",
        "Spondylolisthesis",
        "Bone lesions",
        "Osteomyelitis",
        "Spondylolysis",
        "Bony mineralization",
        "Support devices",
        "Straightening",
        "Spinal deformity",
        "Hardware",
        "Scoliosis",
        "Calcification",
        "Rib notching",
        "Costotransverse joint abnormalities",
        "No findings",
    ],
}


FINEGRAINED_TO_CONSOLIDATED_BY_BODY_PART = {
    "Abdomen": {
        "Bowel obstruction": "Bowel obstruction",
        "Bowel dilation": "Bowel obstruction",
        "Colonic distension": "Bowel obstruction",
        "Air fluid levels": "Bowel obstruction",
        "Pneumoperitoneum": "Pneumoperitoneum",
        "Free air": "Pneumoperitoneum",
        "Calcifications": "Calcifications",
        "Vascular calcifications in abdominal vessels": "Calcifications",
        "Calcified phleboliths": "Calcifications",
        "Heterotopic ossification": "Calcifications",
        "Abnormal calcifications": "Calcifications",
        "Foreign bodies": "Foreign bodies",
        "Organomegaly": "Organomegaly",
        "Masses": "Masses",
        "Ileus": "Ileus",
        "Abnormal gas patterns": "Ileus",
        "Ascites": "Ascites",
        "Stool": "Stool",
        "Constipation": "Stool",
        "Support devices": "Support devices",
        "Pneumatosis intestinalis": "Pneumatosis intestinalis",
        "Portal venous gas": "Portal venous gas",
        "Gallstones": "Gallstones",
        "Renal stones": "Renal stones",
        "Ureteral calculi": "Ureteral calculi",
        "Medical devices": "Medical devices",
        "Ureteral stents": "Medical devices",
        "Surgical clips or staples": "Medical devices",
        "Iud": "Iud",
        "Uterine fibroids": "Uterine fibroids",
        "Degenerative changes": "Degenerative changes",
        "Pneumatosis": "Pneumatosis",
        "Bowel wall thickening": "Bowel wall thickening",
        "Diaphragmatic hernia": "Diaphragmatic hernia",
        "Bladder distension or masses": "Bladder distension or masses",
        "No findings": "No findings",
    },
    "Arm": {
        "Fracture": "Fracture",
        "Scaphoid fracture": "Fracture",
        "Buckle fracture": "Fracture",
        "Bony bankart": "Fracture",
        "Hill sachs": "Fracture",
        "Dislocation": "Dislocation",
        "Joint subluxation": "Dislocation",
        "Acromioclavicular joint separation": "Dislocation",
        "Ac separation": "Dislocation",
        "Joint effusion": "Joint effusion",
        "Soft tissue swelling": "Soft tissue swelling",
        "Subcutaneous gas": "Subcutaneous gas",
        "Foreign bodies": "Foreign bodies",
        "Bone lesions": "Bone lesions",
        "Osteomyelitis": "Osteomyelitis",
        "Periosteal reaction": "Osteomyelitis",
        "Edema": "Osteomyelitis",
        "Erosive change": "Erosive change",
        "Rarefaction": "Erosive change",
        "Osseous destruction": "Erosive change",
        "Bony mineralization": "Bony mineralization",
        "Amputation": "Amputation",
        "Growth plate abnormalities": "Growth plate abnormalities",
        "Hardware complication": "Hardware complication",
        "Malunion": "Malunion",
        "Nonunion": "Malunion",
        "Tendinous calcifications": "Tendinous calcifications",
        "Charcot joint": "Charcot joint",
        "Synostosis": "Synostosis",
        "Degenerative changes": "Degenerative changes",
        "Enthesophytes": "Degenerative changes",
        "Osteophytes": "Degenerative changes",
        "Arthritic changes": "Degenerative changes",
        "Joint space narrowing": "Degenerative changes",
        "Ulnar variance": "Ulnar variance",
        "Soft tissue calcifications": "Soft tissue calcifications",
        "Myositis ossificans": "Soft tissue calcifications",
        "Synostosis between radius and ulna": "Synostosis between radius and ulna",
        "Bone infarcts": "Bone infarcts",
        "Fat pad signs suggesting joint effusion": "Fat pad signs suggesting joint effusion",
        "Os subcoronoideum": "Os subcoronoideum",
        "Os supratrochlear": "Os subcoronoideum",
        "Os acromiale": "Os subcoronoideum",
        "Rotator cuff calcific tendinitis": "Rotator cuff calcific tendinitis",
        "Distal clavicle osteolysis": "Distal clavicle osteolysis",
        "No findings": "No findings",
    },
    "C-spine": {
        "Foreign body": "Foreign body",
        "Foreign bodies": "Foreign body",
        "Fracture": "Fracture",
        "Vertebral height loss": "Fracture",
        "Compression fracture": "Fracture",
        "Vertebral collapse": "Fracture",
        "Odontoid fracture": "Fracture",
        "Hyoid bone fractures or dislocations": "Fracture",
        "Thyroid cartilage fractures": "Fracture",
        "Laryngeal fracture": "Fracture",
        "Degenerative changes": "Degenerative changes",
        "Osteophytes": "Degenerative changes",
        "Intervertebral disc narrowing": "Degenerative changes",
        "Vacuum disc phenomenon": "Degenerative changes",
        "Spondylosis": "Degenerative changes",
        "Facet joint arthropathy": "Degenerative changes",
        "Spinal canal narrowing": "Degenerative changes",
        "Enthesophytes": "Degenerative changes",
        "Uncovertebral joint arthrosis": "Degenerative changes",
        "Neural foraminal narrowing": "Degenerative changes",
        "Dislocation": "Dislocation",
        "Traumatic subluxation": "Dislocation",
        "Atlantoaxial subluxation": "Dislocation",
        "Atlanto-occipital joint abnormalities": "Dislocation",
        "Spondylolisthesis": "Spondylolisthesis",
        "Listhesis": "Spondylolisthesis",
        "Scoliosis": "Scoliosis",
        "Spondylolysis": "Spondylolysis",
        "Bone lesions": "Bone lesions",
        "Osteomyelitis": "Osteomyelitis",
        "Bony mineralization": "Bony mineralization",
        "Support devices": "Support devices",
        "Tracheostomy tube placement abnormalities": "Support devices",
        "Hardware": "Hardware",
        "Hardware malposition": "Hardware",
        "Hardware loosening": "Hardware",
        "Postoperative fusion changes": "Hardware",
        "Spinal deformity": "Spinal deformity",
        "Pseudoarticulation": "Spinal deformity",
        "Schmorls node": "Spinal deformity",
        "Ankylosis": "Spinal deformity",
        "Congenital fusion of cervical vertebrae (klippel-feil syndrome)": "Spinal deformity",
        "Odontoid process sclerosis": "Spinal deformity",
        "Odontoid process fragmentation": "Spinal deformity",
        "Bilateral or unilateral facet joint ankylosis": "Spinal deformity",
        "Tracheal stenosis": "Tracheal stenosis",
        "Tracheal deviation": "Tracheal stenosis",
        "Soft tissue swelling": "Soft tissue swelling",
        "Epiglottitis": "Soft tissue swelling",
        "Airway patency/narrowing": "Soft tissue swelling",
        "Prevertebral soft tissue widening": "Soft tissue swelling",
        "Subglottic narrowing": "Soft tissue swelling",
        "Prevertebral hematoma": "Soft tissue swelling",
        "Pharyngeal soft tissue masses": "Soft tissue swelling",
        "Cervical rib": "Cervical rib",
        "Cervical rib variations": "Cervical rib",
        "Soft tissue emphysema": "Soft tissue emphysema",
        "Retropharyngeal air": "Soft tissue emphysema",
        "Post-surgical air": "Soft tissue emphysema",
        "Soft tissue air tracking from perforation": "Soft tissue emphysema",
        "Calcifications": "Calcifications",
        "Aortic calcifications": "Aortic calcifications",
        "Carotid calcifications": "Calcifications",
        "Ossification of the posterior longitudinal ligament": "Calcifications",
        "Calcific tendinitis of the longus colli muscle": "Calcifications",
        "Cervical spine alignment": "Cervical spine alignment",
        "Kyphosis": "Cervical spine alignment",
        "Lordosis": "Cervical spine alignment",
        "Lateral curvature": "Cervical spine alignment",
        "Straightening": "Cervical spine alignment",
        "Hyoid bone abnormality": "Hyoid bone abnormality",
        "Thyroid enlargement": "Thyroid enlargement",
        "Esophageal dilation": "Esophageal dilation",
        "No findings": "No findings",
    },
    "Chest": {
        "Adenopathy": "Adenopathy",
        "Airspace opacity": "Airspace opacity",
        "Consolidation": "Airspace opacity",
        "Pneumonia": "Airspace opacity",
        "Covid-19": "Airspace opacity",
        "Pneumonitis": "Airspace opacity",
        "Aortic enlargement": "Aortic enlargement",
        "Degenerative changes": "Degenerative changes",
        "Arthritis": "Degenerative changes",
        "Asthma": "Asthma",
        "Atelectasis": "Atelectasis",
        "Bronchitis": "Bronchitis",
        "Calcification": "Calcification",
        "Cardiomegaly": "Cardiomegaly",
        "Pericardial effusion": "Cardiomegaly",
        "Pulmonary contusion": "Pulmonary contusion",
        "Congestive heart failure": "Congestive heart failure",
        "Pulmonary edema": "Congestive heart failure",
        "Kerley b lines": "Congestive heart failure",
        "Venous congestion": "Congestive heart failure",
        "Edema": "Congestive heart failure",
        "Air bronchogram": "Air bronchogram",
        "Emphysema": "Emphysema",
        "Hyperinflation": "Emphysema",
        "Enlarged mediastinum": "Enlarged mediastinum",
        "Enlarged pulmonary artery": "Enlarged pulmonary artery",
        "Fibrosis": "Fibrosis",
        "Fracture": "Fracture",
        "Rib fracture": "Fracture",
        "Granuloma": "Granuloma",
        "Calcified granuloma": "Granuloma",
        "Hiatal hernia": "Hiatal hernia",
        "Hernia": "Hiatal hernia",
        "Pulmonary cavitary lesion": "Pulmonary cavitary lesion",
        "Mass/nodule": "Mass/nodule",
        "Mediastinal shift": "Mediastinal shift",
        "Osteoporosis": "Osteoporosis",
        "Perihilar opacity": "Perihilar opacity",
        "Pleural effusion": "Pleural effusion",
        "Costophrenic angle blunting": "Pleural effusion",
        "Opacified hemithorax": "Pleural effusion",
        "Pleural thickening": "Pleural thickening",
        "Pneumothorax": "Pneumothorax",
        "Lucent hemithorax": "Pneumothorax",
        "Diaphragmatic elevation": "Diaphragmatic elevation",
        "Diaphragmatic eventration": "Diaphragmatic elevation",
        "Diaphragmatic paralysis": "Diaphragmatic elevation",
        "Flattening of the hemi diaphragm": "Diaphragmatic elevation",
        "Sarcoidosis": "Sarcoidosis",
        "Scarring": "Scarring",
        "Tortuous aorta": "Tortuous aorta",
        "Tuberculosis": "Tuberculosis",
        "Pleural plaque": "Pleural plaque",
        "Foreign bodies": "Foreign bodies",
        "Support devices": "Support devices",
        "Endotracheal tube malposition": "Support devices",
        "Nasogastric tube malposition": "Support devices",
        "Tracheostomy tube malposition": "Support devices",
        "Enteric tube": "Support devices",
        "Cardiac devices": "Cardiac devices",
        "Pacemaker leads": "Cardiac devices",
        "Interstitial lung disease (ild)": "Interstitial lung disease (ild)",
        "Bronchiectasis": "Bronchiectasis",
        "Subcutaneous emphysema": "Subcutaneous emphysema",
        "Lung volume loss": "Lung volume loss",
        "Bone lesion": "Bone lesion",
        "Lytic lesions": "Bone lesion",
        "Blastic lesions": "Bone lesion",
        "Spondlyitis": "Bone lesion",
        "Scoliosis": "Scoliosis",
        "Chest wall mass": "Chest wall mass",
        "Tracheal deviation": "Tracheal deviation",
        "Post-surgical changes": "Post-surgical changes",
        "Tracheal stenosis": "Tracheal stenosis",
        "Esophageal dilation": "Esophageal dilation",
        "Pneumomediastinum": "Pneumomediastinum",
        "Pneumoperitoneum": "Pneumoperitoneum",
        "Cervical ribs": "Cervical ribs",
        "Distended bowel": "Distended bowel",
        "No findings": "No findings",
    },
    "Foot": {
        "Fracture": "Fracture",
        "Malunion": "Fracture",
        "Osteochondral lesion": "Fracture",
        "Stress fracture": "Fracture",
        "Avulsion fractures": "Fracture",
        "Dislocation": "Dislocation",
        "Joint subluxation": "Dislocation",
        "Lisfranc": "Dislocation",
        "Claw toe": "Dislocation",
        "Hammer toe": "Dislocation",
        "Arthritic changes": "Arthritic changes",
        "Joint effusion": "Joint effusion",
        "Soft tissue swelling": "Soft tissue swelling",
        "Edema": "Soft tissue swelling",
        "Subcutaneous gas": "Subcutaneous gas",
        "Foreign bodies": "Foreign bodies",
        "Bone lesions": "Bone lesions",
        "Osteomyelitis": "Osteomyelitis",
        "Periosteal reaction": "Osteomyelitis",
        "Degenerative changes": "Degenerative changes",
        "Joint space narrowing": "Degenerative changes",
        "Subchondral cysts": "Degenerative changes",
        "Erosive change": "Erosive change",
        "Osseous destruction": "Erosive change",
        "Bony mineralization": "Bony mineralization",
        "Charcot joint": "Charcot joint",
        "Amputation": "Amputation",
        "Tarsal coalition": "Tarsal coalition",
        "Growth plate abnormalities": "Growth plate abnormalities",
        "Hardware complication": "Hardware complication",
        "Syndesmotic injury": "Syndesmotic injury",
        "Kagers fat pad": "Kagers fat pad",
        "Nonunion": "Kagers fat pad",
        "Tendinous calcifications": "Tendinous calcifications",
        "Hallux valgus": "Hallux valgus",
        "Synostosis": "Synostosis",
        "Soft tissue calcifications": "Soft tissue calcifications",
        "Ossicles": "Ossicles",
        "Accessory ossicles": "Ossicles",
        "Os navicularis": "Ossicles",
        "Os trigonum": "Ossicles",
        "Os interphalangeus": "Ossicles",
        "Rarefaction": "Rarefaction",
        "No findings": "No findings",
    },
    "Hand": {
        "Fracture": "Fracture",
        "Tuft fractures": "Fracture",
        "Buckle fracture": "Fracture",
        "Scaphoid fracture": "Fracture",
        "Tendon avulsion fractures": "Fracture",
        "Dislocation": "Dislocation",
        "Joint subluxation": "Dislocation",
        "Lunate dislocation": "Dislocation",
        "Perilunate dislocation": "Dislocation",
        "Soft tissue swelling": "Soft tissue swelling",
        "Subcutaneous gas": "Soft tissue swelling",
        "Foreign bodies": "Foreign bodies",
        "Bone lesions": "Bone lesions",
        "Osteomyelitis": "Osteomyelitis",
        "Periosteal reaction": "Osteomyelitis",
        "Erosive change": "Erosive change",
        "Rarefaction": "Erosive change",
        "Osseous destruction": "Erosive change",
        "Phalangeal osteolysis": "Erosive change",
        "Bony mineralization": "Bony mineralization",
        "Amputation": "Amputation",
        "Hardware": "Hardware",
        "Hardware complication": "Hardware",
        "Malunion": "Malunion",
        "Nonunion": "Malunion",
        "Tendinous calcifications": "Tendinous calcifications",
        "Soft tissue calcifications": "Tendinous calcifications",
        "Charcot joint": "Charcot joint",
        "Synostosis": "Synostosis",
        "Degenerative changes": "Degenerative changes",
        "Enthesophytes": "Degenerative changes",
        "Osteophytes": "Degenerative changes",
        "Arthritic changes": "Degenerative changes",
        "Joint space narrowing": "Degenerative changes",
        "Ulnar variance": "Ulnar variance",
        "Ossicles": "Ossicles",
        "Os interphalangeus": "Ossicles",
        "Edema": "Edema",
        "Boutonniere deformity": "Boutonniere deformity",
        "Swan neck deformity": "Boutonniere deformity",
        "Trigger finger deformity signs": "Boutonniere deformity",
        "Madelung deformity": "Boutonniere deformity",
        "Carpal coalition": "Carpal coalition",
        "Avascular necrosis": "Avascular necrosis",
        "Acro-osteolysis": "Acro-osteolysis",
        "Carpal boss": "Carpal boss",
        "Enostosis": "Enostosis",
        "Scaphoid avascular necrosis (kienbocks disease)": "Scaphoid avascular necrosis (kienbocks disease)",
        "No findings": "No findings",
    },
    "Head": {
        "Fracture": "Fracture",
        "Pathological fracture": "Fracture",
        "Nonunion": "Fracture",
        "Malunion": "Fracture",
        "Dislocation": "Dislocation",
        "Joint subluxation": "Dislocation",
        "Soft tissue swelling": "Soft tissue swelling",
        "Orbital emphysema": "Orbital emphysema",
        "Subcutaneous gas": "Orbital emphysema",
        "Foreign bodies": "Foreign bodies",
        "Metallic foreign body": "Foreign bodies",
        "Intracranial foreign body": "Foreign bodies",
        "Dental artifacts": "Foreign bodies",
        "Periosteal reaction": "Periosteal reaction",
        "Osteomyelitis": "Periosteal reaction",
        "Erosive change": "Erosive change",
        "Bony mineralization": "Bony mineralization",
        "Support devices": "Support devices",
        "Hardware complication": "Support devices",
        "Shunt tubing or valves": "Support devices",
        "Degenerative changes": "Degenerative changes",
        "Arthritic changes": "Degenerative changes",
        "Joint space narrowing": "Degenerative changes",
        "Pneumocephalus": "Pneumocephalus",
        "Calvarial lesions": "Calvarial lesions",
        "Aplastic": "Calvarial lesions",
        "Aplasia": "Calvarial lesions",
        "Osseous destruction": "Calvarial lesions",
        "Bone lesions": "Calvarial lesions",
        "Skull base asymmetry": "Calvarial lesions",
        "Sutural diastasis": "Calvarial lesions",
        "Hypoplastic sinus": "Calvarial lesions",
        "Paranasal sinus expansion": "Calvarial lesions",
        "Soft tissue calcifications": "Soft tissue calcifications",
        "Abnormal calcifications": "Soft tissue calcifications",
        "Sinusitis": "Sinusitis",
        "Air-fluid levels": "Sinusitis",
        "Mucosal thickening": "Sinusitis",
        "Mastoid opacity": "Mastoid opacity",
        "Middle ear effusion": "Mastoid opacity",
        "Post-surgical changes": "Post-surgical changes",
        "Craniotomy": "Post-surgical changes",
        "Rarefaction": "Rarefaction",
        "No findings": "No findings",
    },
    "L-spine": {
        "Fracture": "Fracture",
        "Vertebral height loss": "Fracture",
        "Compression fracture": "Fracture",
        "Vertebral collapse": "Fracture",
        "Degenerative changes": "Degenerative changes",
        "Osteophytes": "Degenerative changes",
        "Intervertebral disc narrowing": "Degenerative changes",
        "Vacuum disc phenomenon": "Degenerative changes",
        "Spondylosis": "Degenerative changes",
        "Facet joint arthropathy": "Degenerative changes",
        "Spinal canal narrowing": "Degenerative changes",
        "Enthesophytes": "Degenerative changes",
        "Spondylolisthesis": "Spondylolisthesis",
        "Scoliosis": "Scoliosis",
        "Lateral curvature": "Scoliosis",
        "Scoliosis with rotational deformities": "Scoliosis",
        "Hardware": "Hardware",
        "Hardware malposition": "Hardware",
        "Hardware loosening": "Hardware",
        "Postoperative fusion changes": "Hardware",
        "Support devices": "Support devices",
        "Bone lesions": "Bone lesions",
        "Osteomyelitis": "Osteomyelitis",
        "Bony mineralization": "Bony mineralization",
        "Sacroiliitis": "Sacroiliitis",
        "Spinal deformity": "Spinal deformity",
        "Pseudoarticulation": "Spinal deformity",
        "Schmorls node": "Spinal deformity",
        "Ankylosis": "Spinal deformity",
        "Spina bifida occulta": "Spinal deformity",
        "Sacralization of l5": "Spinal deformity",
        "Lumbarization of s1": "Spinal deformity",
        "Transitional vertebrae": "Spinal deformity",
        "Transitional sacral vertebrae anomalies": "Spinal deformity",
        "Pars interarticularis defects": "Spinal deformity",
        "Spondylolysis": "Spinal deformity",
        "Calcification": "Calcification",
        "Aortic calcifications": "Calcification",
        "Ossification of the posterior longitudinal ligament": "Calcification",
        "Iliolumbar ligament calcifications or ossifications": "Calcification",
        "Calcification of interspinous ligaments": "Calcification",
        "Straightening": "Straightening",
        "Kyphosis": "Straightening",
        "Lordosis": "Straightening",
        "No findings": "No findings",
    },
    "Leg": {
        "Fracture": "Fracture",
        "Stress reaction": "Fracture",
        "Malunion": "Fracture",
        "Nonunion": "Fracture",
        "Stress fracture callus formation": "Fracture",
        "Dislocation": "Dislocation",
        "Joint subluxation": "Dislocation",
        "Degenerative changes": "Degenerative changes",
        "Enthesophytes": "Degenerative changes",
        "Osteophytes": "Degenerative changes",
        "Subchondral cyst": "Degenerative changes",
        "Arthritic changes": "Degenerative changes",
        "Osteochondral defects": "Degenerative changes",
        "Joint space narrowing": "Degenerative changes",
        "Joint effusion": "Joint effusion",
        "Soft tissue swelling": "Soft tissue swelling",
        "Edema": "Soft tissue swelling",
        "Subcutaneous gas": "Subcutaneous gas",
        "Foreign bodies": "Foreign bodies",
        "Bone lesions": "Bone lesions",
        "Osteomyelitis": "Osteomyelitis",
        "Periosteal reaction": "Osteomyelitis",
        "Erosive change": "Erosive change",
        "Rarefaction": "Erosive change",
        "Osseous destruction": "Erosive change",
        "Bony mineralization": "Bony mineralization",
        "Hardware": "Hardware",
        "Hardware complication": "Hardware",
        "Loosening of hardware": "Hardware",
        "Migration of hardware": "Hardware",
        "Amputation": "Amputation",
        "Growth plate abnormalities": "Growth plate abnormalities",
        "Tendinous calcifications": "Tendinous calcifications",
        "Soft tissue calcifications": "Tendinous calcifications",
        "Charcot joint": "Charcot joint",
        "Limb-length discrepancy": "Limb-length discrepancy",
        "Synostosis": "Synostosis",
        "Femoral acetabular impingement": "Femoral acetabular impingement",
        "Fai": "Femoral acetabular impingement",
        "Cam deformity": "Femoral acetabular impingement",
        "Cortical thickening": "Cortical thickening",
        "Bone infarcts": "Bone infarcts",
        "Heterotopic ossification": "Heterotopic ossification",
        "Myositis ossificans": "Heterotopic ossification",
        "Calcifications": "Calcifications",
        "Meniscal calcifications": "Calcifications",
        "Patellar tracking abnormalities": "Patellar tracking abnormalities",
        "Bipartite patella": "Bipartite patella",
        "Osteochondritis dissecans": "Osteochondritis dissecans",
        "Intraarticular bodies": "Intraarticular bodies",
        "Osteochondral lesions": "Osteochondral lesions",
        "No findings": "No findings",
    },
    "Pelvis": {
        "Fracture": "Fracture",
        "Dislocation": "Dislocation",
        "Joint widening": "Dislocation",
        "Pubic symphysis diastasis": "Dislocation",
        "Bone lesions": "Bone lesions",
        "Avascular necrosis": "Avascular necrosis",
        "Soft tissue swelling": "Soft tissue swelling",
        "Subcutaneous gas": "Subcutaneous gas",
        "Osteomyelitis": "Osteomyelitis",
        "Bony mineralization": "Bony mineralization",
        "Medical devices": "Medical devices",
        "Urologic stent": "Medical devices",
        "Foley catheter": "Medical devices",
        "Iud": "Iud",
        "Soft tissue mass": "Soft tissue mass",
        "Intra-articular body": "Intra-articular body",
        "Ureteral calculi": "Ureteral calculi",
        "Degenerative changes": "Degenerative changes",
        "Enthesopathy": "Degenerative changes",
        "Arthritis": "Degenerative changes",
        "Subchondral cyst": "Degenerative changes",
        "Sacralization of spine": "Sacralization of spine",
        "Stool": "Stool",
        "Constipation": "Stool",
        "Cam deformity": "Cam deformity",
        "Slipped capital femoral epiphysis": "Slipped capital femoral epiphysis",
        "Femoral acetabular impingement": "Femoral acetabular impingement",
        "Protrusio acetabuli": "Protrusio acetabuli",
        "Osteochondral defects": "Osteochondral defects",
        "Heterotopic ossification": "Heterotopic ossification",
        "Soft tissue calcifications": "Heterotopic ossification",
        "Acetabular retroversion sign": "Acetabular retroversion sign",
        "Crossover sign": "Crossover sign",
        "Sacroiliitis": "Sacroiliitis",
        "Osteitis condensans ilii": "Osteitis condensans ilii",
        "Osteitis pubis": "Osteitis pubis",
        "Pelvic vascular calcifications": "Pelvic vascular calcifications",
        "Pelvic phleboliths": "Pelvic vascular calcifications",
        "No findings": "No findings",
    },
    "T-spine": {
        "Fracture": "Fracture",
        "Vertebral height loss": "Fracture",
        "Compression fracture": "Fracture",
        "Vertebral collapse": "Fracture",
        "Rib head fractures or dislocations": "Fracture",
        "Degenerative changes": "Degenerative changes",
        "Osteophytes": "Degenerative changes",
        "Intervertebral disc narrowing": "Degenerative changes",
        "Vacuum disc phenomenon": "Degenerative changes",
        "Spondylosis": "Degenerative changes",
        "Facet joint arthropathy": "Degenerative changes",
        "Spinal canal narrowing": "Degenerative changes",
        "Enthesophytes": "Degenerative changes",
        "Costovertebral joint arthropathy": "Degenerative changes",
        "Spondylolisthesis": "Spondylolisthesis",
        "Bone lesions": "Bone lesions",
        "Absent pedicle": "Bone lesions",
        "Osteomyelitis": "Osteomyelitis",
        "Spondylolysis": "Spinal deformity",
        "Bony mineralization": "Bony mineralization",
        "Support devices": "Support devices",
        "Straightening": "Straightening",
        "Kyphosis": "Straightening",
        "Lordosis": "Straightening",
        "Spinal deformity": "Spinal deformity",
        "Pseudoarticulation": "Spinal deformity",
        "Schmorls node": "Spinal deformity",
        "Ankylosis": "Spinal deformity",
        "Spina bifida occulta": "Spinal deformity",
        "Butterfly vertebra": "Spinal deformity",
        "Hemivertebra": "Spinal deformity",
        "Block vertebrae": "Spinal deformity",
        "Pars interarticularis defects": "Spinal deformity",
        "Hardware": "Hardware",
        "Hardware malposition": "Hardware",
        "Hardware loosening": "Hardware",
        "Postoperative fusion changes": "Hardware",
        "Scoliosis": "Scoliosis",
        "Lateral curvature": "Scoliosis",
        "Scoliosis with rotational deformities": "Scoliosis",
        "Levoconvex": "Scoliosis",
        "Dextroconvex": "Scoliosis",
        "Calcification": "Calcification",
        "Aortic calcifications": "Calcification",
        "Ossification of the posterior longitudinal ligament": "Calcification",
        "Calcification of interspinous ligaments": "Calcification",
        "Ossification of the ligamentum flavum": "Calcification",
        "Rib notching": "Rib notching",
        "Costotransverse joint abnormalities": "Costotransverse joint abnormalities",
        "No findings": "No findings",
    },
}

CONSOLIDATED_TO_FINEGRAINED_BY_BODY_PART = {
    "Abdomen": {
        "Bowel obstruction": [
            "Bowel obstruction",
            "Bowel dilation",
            "Colonic distension",
            "Air fluid levels",
        ],
        "Pneumoperitoneum": ["Pneumoperitoneum", "Free air"],
        "Calcifications": [
            "Calcifications",
            "Vascular calcifications in abdominal vessels",
            "Calcified phleboliths",
            "Heterotopic ossification",
            "Abnormal calcifications",
        ],
        "Foreign bodies": ["Foreign bodies"],
        "Organomegaly": ["Organomegaly"],
        "Masses": ["Masses"],
        "Ileus": ["Ileus", "Abnormal gas patterns"],
        "Ascites": ["Ascites"],
        "Stool": ["Stool", "Constipation"],
        "Support devices": ["Support devices"],
        "Pneumatosis intestinalis": ["Pneumatosis intestinalis"],
        "Portal venous gas": ["Portal venous gas"],
        "Gallstones": ["Gallstones"],
        "Renal stones": ["Renal stones"],
        "Ureteral calculi": ["Ureteral calculi"],
        "Medical devices": [
            "Medical devices",
            "Ureteral stents",
            "Surgical clips or staples",
        ],
        "Iud": ["Iud"],
        "Uterine fibroids": ["Uterine fibroids"],
        "Degenerative changes": ["Degenerative changes"],
        "Pneumatosis": ["Pneumatosis"],
        "Bowel wall thickening": ["Bowel wall thickening"],
        "Diaphragmatic hernia": ["Diaphragmatic hernia"],
        "Bladder distension or masses": ["Bladder distension or masses"],
        "No findings": ["No findings"],
    },
    "Arm": {
        "Fracture": [
            "Fracture",
            "Scaphoid fracture",
            "Buckle fracture",
            "Bony bankart",
            "Hill sachs",
        ],
        "Dislocation": [
            "Dislocation",
            "Joint subluxation",
            "Acromioclavicular joint separation",
            "Ac separation",
        ],
        "Joint effusion": ["Joint effusion"],
        "Soft tissue swelling": ["Soft tissue swelling"],
        "Subcutaneous gas": ["Subcutaneous gas"],
        "Foreign bodies": ["Foreign bodies"],
        "Bone lesions": ["Bone lesions"],
        "Osteomyelitis": ["Osteomyelitis", "Periosteal reaction", "Edema"],
        "Erosive change": ["Erosive change", "Rarefaction", "Osseous destruction"],
        "Bony mineralization": ["Bony mineralization"],
        "Amputation": ["Amputation"],
        "Growth plate abnormalities": ["Growth plate abnormalities"],
        "Hardware complication": ["Hardware complication"],
        "Malunion": ["Malunion", "Nonunion"],
        "Tendinous calcifications": ["Tendinous calcifications"],
        "Charcot joint": ["Charcot joint"],
        "Synostosis": ["Synostosis"],
        "Degenerative changes": [
            "Degenerative changes",
            "Enthesophytes",
            "Osteophytes",
            "Arthritic changes",
            "Joint space narrowing",
        ],
        "Ulnar variance": ["Ulnar variance"],
        "Soft tissue calcifications": [
            "Soft tissue calcifications",
            "Myositis ossificans",
        ],
        "Synostosis between radius and ulna": ["Synostosis between radius and ulna"],
        "Bone infarcts": ["Bone infarcts"],
        "Fat pad signs suggesting joint effusion": [
            "Fat pad signs suggesting joint effusion"
        ],
        "Os subcoronoideum": ["Os subcoronoideum", "Os supratrochlear", "Os acromiale"],
        "Rotator cuff calcific tendinitis": ["Rotator cuff calcific tendinitis"],
        "Distal clavicle osteolysis": ["Distal clavicle osteolysis"],
        "No findings": ["No findings"],
    },
    "C-spine": {
        "Foreign body": ["Foreign body", "Foreign bodies"],
        "Fracture": [
            "Fracture",
            "Vertebral height loss",
            "Compression fracture",
            "Vertebral collapse",
            "Odontoid fracture",
            "Hyoid bone fractures or dislocations",
            "Thyroid cartilage fractures",
            "Laryngeal fracture",
        ],
        "Degenerative changes": [
            "Degenerative changes",
            "Osteophytes",
            "Intervertebral disc narrowing",
            "Vacuum disc phenomenon",
            "Spondylosis",
            "Facet joint arthropathy",
            "Spinal canal narrowing",
            "Enthesophytes",
            "Uncovertebral joint arthrosis",
            "Neural foraminal narrowing",
        ],
        "Dislocation": [
            "Dislocation",
            "Traumatic subluxation",
            "Atlantoaxial subluxation",
            "Atlanto-occipital joint abnormalities",
        ],
        "Spondylolisthesis": ["Spondylolisthesis", "Listhesis"],
        "Scoliosis": ["Scoliosis"],
        "Spondylolysis": ["Spondylolysis"],
        "Bone lesions": ["Bone lesions"],
        "Osteomyelitis": ["Osteomyelitis"],
        "Bony mineralization": ["Bony mineralization"],
        "Support devices": [
            "Support devices",
            "Tracheostomy tube placement abnormalities",
        ],
        "Hardware": [
            "Hardware",
            "Hardware malposition",
            "Hardware loosening",
            "Postoperative fusion changes",
        ],
        "Spinal deformity": [
            "Spinal deformity",
            "Pseudoarticulation",
            "Schmorls node",
            "Ankylosis",
            "Congenital fusion of cervical vertebrae (klippel-feil syndrome)",
            "Odontoid process sclerosis",
            "Odontoid process fragmentation",
            "Bilateral or unilateral facet joint ankylosis",
        ],
        "Tracheal stenosis": ["Tracheal stenosis", "Tracheal deviation"],
        "Soft tissue swelling": [
            "Soft tissue swelling",
            "Epiglottitis",
            "Airway patency/narrowing",
            "Prevertebral soft tissue widening",
            "Subglottic narrowing",
            "Prevertebral hematoma",
            "Pharyngeal soft tissue masses",
        ],
        "Cervical rib": ["Cervical rib", "Cervical rib variations"],
        "Soft tissue emphysema": [
            "Soft tissue emphysema",
            "Retropharyngeal air",
            "Post-surgical air",
            "Soft tissue air tracking from perforation",
        ],
        "Calcifications": [
            "Calcifications",
            "Aortic calcifications",
            "Carotid calcifications",
            "Ossification of the posterior longitudinal ligament",
            "Calcific tendinitis of the longus colli muscle",
        ],
        "Aortic calcifications": ["Aortic calcifications"],
        "Cervical spine alignment": [
            "Cervical spine alignment",
            "Kyphosis",
            "Lordosis",
            "Lateral curvature",
            "Straightening",
        ],
        "Hyoid bone abnormality": ["Hyoid bone abnormality"],
        "Thyroid enlargement": ["Thyroid enlargement"],
        "Esophageal dilation": ["Esophageal dilation"],
        "No findings": ["No findings"],
    },
    "Chest": {
        "Adenopathy": ["Adenopathy"],
        "Airspace opacity": [
            "Airspace opacity",
            "Consolidation",
            "Pneumonia",
            "Covid-19",
            "Pneumonitis",
        ],
        "Aortic enlargement": ["Aortic enlargement"],
        "Degenerative changes": ["Degenerative changes", "Arthritis"],
        "Asthma": ["Asthma"],
        "Atelectasis": ["Atelectasis"],
        "Bronchitis": ["Bronchitis"],
        "Calcification": ["Calcification"],
        "Cardiomegaly": ["Cardiomegaly", "Pericardial effusion"],
        "Pulmonary contusion": ["Pulmonary contusion"],
        "Congestive heart failure": [
            "Congestive heart failure",
            "Pulmonary edema",
            "Kerley b lines",
            "Venous congestion",
            "Edema",
        ],
        "Air bronchogram": ["Air bronchogram"],
        "Emphysema": ["Emphysema", "Hyperinflation"],
        "Enlarged mediastinum": ["Enlarged mediastinum"],
        "Enlarged pulmonary artery": ["Enlarged pulmonary artery"],
        "Fibrosis": ["Fibrosis"],
        "Fracture": ["Fracture", "Rib fracture"],
        "Granuloma": ["Granuloma", "Calcified granuloma"],
        "Hiatal hernia": ["Hiatal hernia", "Hernia"],
        "Pulmonary cavitary lesion": ["Pulmonary cavitary lesion"],
        "Mass/nodule": ["Mass/nodule"],
        "Mediastinal shift": ["Mediastinal shift"],
        "Osteoporosis": ["Osteoporosis"],
        "Perihilar opacity": ["Perihilar opacity"],
        "Pleural effusion": [
            "Pleural effusion",
            "Costophrenic angle blunting",
            "Opacified hemithorax",
        ],
        "Pleural thickening": ["Pleural thickening"],
        "Pneumothorax": ["Pneumothorax", "Lucent hemithorax"],
        "Diaphragmatic elevation": [
            "Diaphragmatic elevation",
            "Diaphragmatic eventration",
            "Diaphragmatic paralysis",
            "Flattening of the hemi diaphragm",
        ],
        "Sarcoidosis": ["Sarcoidosis"],
        "Scarring": ["Scarring"],
        "Tortuous aorta": ["Tortuous aorta"],
        "Tuberculosis": ["Tuberculosis"],
        "Pleural plaque": ["Pleural plaque"],
        "Foreign bodies": ["Foreign bodies"],
        "Support devices": [
            "Support devices",
            "Endotracheal tube malposition",
            "Nasogastric tube malposition",
            "Tracheostomy tube malposition",
            "Enteric tube",
        ],
        "Cardiac devices": ["Cardiac devices", "Pacemaker leads"],
        "Interstitial lung disease (ild)": ["Interstitial lung disease (ild)"],
        "Bronchiectasis": ["Bronchiectasis"],
        "Subcutaneous emphysema": ["Subcutaneous emphysema"],
        "Lung volume loss": ["Lung volume loss"],
        "Bone lesion": [
            "Bone lesion",
            "Lytic lesions",
            "Blastic lesions",
            "Spondlyitis",
        ],
        "Scoliosis": ["Scoliosis"],
        "Chest wall mass": ["Chest wall mass"],
        "Tracheal deviation": ["Tracheal deviation"],
        "Post-surgical changes": ["Post-surgical changes"],
        "Tracheal stenosis": ["Tracheal stenosis"],
        "Esophageal dilation": ["Esophageal dilation"],
        "Pneumomediastinum": ["Pneumomediastinum"],
        "Pneumoperitoneum": ["Pneumoperitoneum"],
        "Cervical ribs": ["Cervical ribs"],
        "Distended bowel": ["Distended bowel"],
        "No findings": ["No findings"],
    },
    "Foot": {
        "Fracture": [
            "Fracture",
            "Malunion",
            "Osteochondral lesion",
            "Stress fracture",
            "Avulsion fractures",
        ],
        "Dislocation": [
            "Dislocation",
            "Joint subluxation",
            "Lisfranc",
            "Claw toe",
            "Hammer toe",
        ],
        "Arthritic changes": ["Arthritic changes"],
        "Joint effusion": ["Joint effusion"],
        "Soft tissue swelling": ["Soft tissue swelling", "Edema"],
        "Subcutaneous gas": ["Subcutaneous gas"],
        "Foreign bodies": ["Foreign bodies"],
        "Bone lesions": ["Bone lesions"],
        "Osteomyelitis": ["Osteomyelitis", "Periosteal reaction"],
        "Degenerative changes": [
            "Degenerative changes",
            "Joint space narrowing",
            "Subchondral cysts",
        ],
        "Erosive change": ["Erosive change", "Osseous destruction"],
        "Bony mineralization": ["Bony mineralization"],
        "Charcot joint": ["Charcot joint"],
        "Amputation": ["Amputation"],
        "Tarsal coalition": ["Tarsal coalition"],
        "Growth plate abnormalities": ["Growth plate abnormalities"],
        "Hardware complication": ["Hardware complication"],
        "Syndesmotic injury": ["Syndesmotic injury"],
        "Kagers fat pad": ["Kagers fat pad", "Nonunion"],
        "Tendinous calcifications": ["Tendinous calcifications"],
        "Hallux valgus": ["Hallux valgus"],
        "Synostosis": ["Synostosis"],
        "Soft tissue calcifications": ["Soft tissue calcifications"],
        "Ossicles": [
            "Ossicles",
            "Accessory ossicles",
            "Os navicularis",
            "Os trigonum",
            "Os interphalangeus",
        ],
        "Rarefaction": ["Rarefaction"],
        "No findings": ["No findings"],
    },
    "Hand": {
        "Fracture": [
            "Fracture",
            "Tuft fractures",
            "Buckle fracture",
            "Scaphoid fracture",
            "Tendon avulsion fractures",
        ],
        "Dislocation": [
            "Dislocation",
            "Joint subluxation",
            "Lunate dislocation",
            "Perilunate dislocation",
        ],
        "Soft tissue swelling": ["Soft tissue swelling", "Subcutaneous gas"],
        "Foreign bodies": ["Foreign bodies"],
        "Bone lesions": ["Bone lesions"],
        "Osteomyelitis": ["Osteomyelitis", "Periosteal reaction"],
        "Erosive change": [
            "Erosive change",
            "Rarefaction",
            "Osseous destruction",
            "Phalangeal osteolysis",
        ],
        "Bony mineralization": ["Bony mineralization"],
        "Amputation": ["Amputation"],
        "Hardware": ["Hardware", "Hardware complication"],
        "Malunion": ["Malunion", "Nonunion"],
        "Tendinous calcifications": [
            "Tendinous calcifications",
            "Soft tissue calcifications",
        ],
        "Charcot joint": ["Charcot joint"],
        "Synostosis": ["Synostosis"],
        "Degenerative changes": [
            "Degenerative changes",
            "Enthesophytes",
            "Osteophytes",
            "Arthritic changes",
            "Joint space narrowing",
        ],
        "Ulnar variance": ["Ulnar variance"],
        "Ossicles": ["Ossicles", "Os interphalangeus"],
        "Edema": ["Edema"],
        "Boutonniere deformity": [
            "Boutonniere deformity",
            "Swan neck deformity",
            "Trigger finger deformity signs",
            "Madelung deformity",
        ],
        "Carpal coalition": ["Carpal coalition"],
        "Avascular necrosis": ["Avascular necrosis"],
        "Acro-osteolysis": ["Acro-osteolysis"],
        "Carpal boss": ["Carpal boss"],
        "Enostosis": ["Enostosis"],
        "Scaphoid avascular necrosis (kienbocks disease)": [
            "Scaphoid avascular necrosis (kienbocks disease)"
        ],
        "No findings": ["No findings"],
    },
    "Head": {
        "Fracture": ["Fracture", "Pathological fracture", "Nonunion", "Malunion"],
        "Dislocation": ["Dislocation", "Joint subluxation"],
        "Soft tissue swelling": ["Soft tissue swelling"],
        "Orbital emphysema": ["Orbital emphysema", "Subcutaneous gas"],
        "Foreign bodies": [
            "Foreign bodies",
            "Metallic foreign body",
            "Intracranial foreign body",
            "Dental artifacts",
        ],
        "Periosteal reaction": ["Periosteal reaction", "Osteomyelitis"],
        "Erosive change": ["Erosive change"],
        "Bony mineralization": ["Bony mineralization"],
        "Support devices": [
            "Support devices",
            "Hardware complication",
            "Shunt tubing or valves",
        ],
        "Degenerative changes": [
            "Degenerative changes",
            "Arthritic changes",
            "Joint space narrowing",
        ],
        "Pneumocephalus": ["Pneumocephalus"],
        "Calvarial lesions": [
            "Calvarial lesions",
            "Aplastic",
            "Aplasia",
            "Osseous destruction",
            "Bone lesions",
            "Skull base asymmetry",
            "Sutural diastasis",
            "Hypoplastic sinus",
            "Paranasal sinus expansion",
        ],
        "Soft tissue calcifications": [
            "Soft tissue calcifications",
            "Abnormal calcifications",
        ],
        "Sinusitis": ["Sinusitis", "Air-fluid levels", "Mucosal thickening"],
        "Mastoid opacity": ["Mastoid opacity", "Middle ear effusion"],
        "Post-surgical changes": ["Post-surgical changes", "Craniotomy"],
        "Rarefaction": ["Rarefaction"],
        "No findings": ["No findings"],
    },
    "L-spine": {
        "Fracture": [
            "Fracture",
            "Vertebral height loss",
            "Compression fracture",
            "Vertebral collapse",
        ],
        "Degenerative changes": [
            "Degenerative changes",
            "Osteophytes",
            "Intervertebral disc narrowing",
            "Vacuum disc phenomenon",
            "Spondylosis",
            "Facet joint arthropathy",
            "Spinal canal narrowing",
            "Enthesophytes",
        ],
        "Spondylolisthesis": ["Spondylolisthesis"],
        "Scoliosis": [
            "Scoliosis",
            "Lateral curvature",
            "Scoliosis with rotational deformities",
        ],
        "Hardware": [
            "Hardware",
            "Hardware malposition",
            "Hardware loosening",
            "Postoperative fusion changes",
        ],
        "Support devices": ["Support devices"],
        "Bone lesions": ["Bone lesions"],
        "Osteomyelitis": ["Osteomyelitis"],
        "Bony mineralization": ["Bony mineralization"],
        "Sacroiliitis": ["Sacroiliitis"],
        "Spinal deformity": [
            "Spinal deformity",
            "Pseudoarticulation",
            "Schmorls node",
            "Ankylosis",
            "Spina bifida occulta",
            "Sacralization of l5",
            "Lumbarization of s1",
            "Transitional vertebrae",
            "Transitional sacral vertebrae anomalies",
            "Pars interarticularis defects",
            "Spondylolysis",
        ],
        "Calcification": [
            "Calcification",
            "Aortic calcifications",
            "Ossification of the posterior longitudinal ligament",
            "Iliolumbar ligament calcifications or ossifications",
            "Calcification of interspinous ligaments",
        ],
        "Straightening": ["Straightening", "Kyphosis", "Lordosis"],
        "No findings": ["No findings"],
    },
    "Leg": {
        "Fracture": [
            "Fracture",
            "Stress reaction",
            "Malunion",
            "Nonunion",
            "Stress fracture callus formation",
        ],
        "Dislocation": ["Dislocation", "Joint subluxation"],
        "Degenerative changes": [
            "Degenerative changes",
            "Enthesophytes",
            "Osteophytes",
            "Subchondral cyst",
            "Arthritic changes",
            "Osteochondral defects",
            "Joint space narrowing",
        ],
        "Joint effusion": ["Joint effusion"],
        "Soft tissue swelling": ["Soft tissue swelling", "Edema"],
        "Subcutaneous gas": ["Subcutaneous gas"],
        "Foreign bodies": ["Foreign bodies"],
        "Bone lesions": ["Bone lesions"],
        "Osteomyelitis": ["Osteomyelitis", "Periosteal reaction"],
        "Erosive change": ["Erosive change", "Rarefaction", "Osseous destruction"],
        "Bony mineralization": ["Bony mineralization"],
        "Hardware": [
            "Hardware",
            "Hardware complication",
            "Loosening of hardware",
            "Migration of hardware",
        ],
        "Amputation": ["Amputation"],
        "Growth plate abnormalities": ["Growth plate abnormalities"],
        "Tendinous calcifications": [
            "Tendinous calcifications",
            "Soft tissue calcifications",
        ],
        "Charcot joint": ["Charcot joint"],
        "Limb-length discrepancy": ["Limb-length discrepancy"],
        "Synostosis": ["Synostosis"],
        "Femoral acetabular impingement": [
            "Femoral acetabular impingement",
            "Fai",
            "Cam deformity",
        ],
        "Cortical thickening": ["Cortical thickening"],
        "Bone infarcts": ["Bone infarcts"],
        "Heterotopic ossification": ["Heterotopic ossification", "Myositis ossificans"],
        "Calcifications": ["Calcifications", "Meniscal calcifications"],
        "Patellar tracking abnormalities": ["Patellar tracking abnormalities"],
        "Bipartite patella": ["Bipartite patella"],
        "Osteochondritis dissecans": ["Osteochondritis dissecans"],
        "Intraarticular bodies": ["Intraarticular bodies"],
        "Osteochondral lesions": ["Osteochondral lesions"],
        "No findings": ["No findings"],
    },
    "Pelvis": {
        "Fracture": ["Fracture"],
        "Dislocation": ["Dislocation", "Joint widening", "Pubic symphysis diastasis"],
        "Bone lesions": ["Bone lesions"],
        "Avascular necrosis": ["Avascular necrosis"],
        "Soft tissue swelling": ["Soft tissue swelling"],
        "Subcutaneous gas": ["Subcutaneous gas"],
        "Osteomyelitis": ["Osteomyelitis"],
        "Bony mineralization": ["Bony mineralization"],
        "Medical devices": ["Medical devices", "Urologic stent", "Foley catheter"],
        "Iud": ["Iud"],
        "Soft tissue mass": ["Soft tissue mass"],
        "Intra-articular body": ["Intra-articular body"],
        "Ureteral calculi": ["Ureteral calculi"],
        "Degenerative changes": [
            "Degenerative changes",
            "Enthesopathy",
            "Arthritis",
            "Subchondral cyst",
        ],
        "Sacralization of spine": ["Sacralization of spine"],
        "Stool": ["Stool", "Constipation"],
        "Cam deformity": ["Cam deformity"],
        "Slipped capital femoral epiphysis": ["Slipped capital femoral epiphysis"],
        "Femoral acetabular impingement": ["Femoral acetabular impingement"],
        "Protrusio acetabuli": ["Protrusio acetabuli"],
        "Osteochondral defects": ["Osteochondral defects"],
        "Heterotopic ossification": [
            "Heterotopic ossification",
            "Soft tissue calcifications",
        ],
        "Acetabular retroversion sign": ["Acetabular retroversion sign"],
        "Crossover sign": ["Crossover sign"],
        "Sacroiliitis": ["Sacroiliitis"],
        "Osteitis condensans ilii": ["Osteitis condensans ilii"],
        "Osteitis pubis": ["Osteitis pubis"],
        "Pelvic vascular calcifications": [
            "Pelvic vascular calcifications",
            "Pelvic phleboliths",
        ],
        "No findings": ["No findings"],
    },
    "T-spine": {
        "Fracture": [
            "Fracture",
            "Vertebral height loss",
            "Compression fracture",
            "Vertebral collapse",
            "Rib head fractures or dislocations",
        ],
        "Degenerative changes": [
            "Degenerative changes",
            "Osteophytes",
            "Intervertebral disc narrowing",
            "Vacuum disc phenomenon",
            "Spondylosis",
            "Facet joint arthropathy",
            "Spinal canal narrowing",
            "Enthesophytes",
            "Costovertebral joint arthropathy",
        ],
        "Spondylolisthesis": ["Spondylolisthesis"],
        "Bone lesions": ["Bone lesions", "Absent pedicle"],
        "Osteomyelitis": ["Osteomyelitis"],
        "Spondylolysis": ["Spondylolysis"],
        "Bony mineralization": ["Bony mineralization"],
        "Support devices": ["Support devices"],
        "Straightening": ["Straightening", "Kyphosis", "Lordosis"],
        "Spinal deformity": [
            "Spinal deformity",
            "Pseudoarticulation",
            "Schmorls node",
            "Ankylosis",
            "Spina bifida occulta",
            "Butterfly vertebra",
            "Hemivertebra",
            "Block vertebrae",
            "Pars interarticularis defects",
            "Spondylolysis",
        ],
        "Hardware": [
            "Hardware",
            "Hardware malposition",
            "Hardware loosening",
            "Postoperative fusion changes",
        ],
        "Scoliosis": [
            "Scoliosis",
            "Lateral curvature",
            "Scoliosis with rotational deformities",
            "Levoconvex",
            "Dextroconvex",
        ],
        "Calcification": [
            "Calcification",
            "Aortic calcifications",
            "Ossification of the posterior longitudinal ligament",
            "Calcification of interspinous ligaments",
            "Ossification of the ligamentum flavum",
        ],
        "Rib notching": ["Rib notching"],
        "Costotransverse joint abnormalities": ["Costotransverse joint abnormalities"],
        "No findings": ["No findings"],
    },
}
