LABELS_BY_BODY_PART = {
    "Head": [
        "Fracture",
        "Dislocation",
        "Arthritic changes",
        "Joint effusion",
        "Soft tissue swelling",
        "Subcutaneous gas",
        "Foreign bodies",
        "Metallic foreign body",
        "Bone lesions",
        "Osteomyelitis",
        "Periosteal reaction",
        "Erosive change",
        "Bony mineralization",
        "Support devices",
        "No findings",
        "Joint subluxation",
        "Hardware complication",
        "Nonunion",
        "Malunion",
        "Degenerative changes",
        "Enthesophytes",
        "Osteophytes",
        "Soft tissue calcifications",
        "Pathological fracture",
        "Ossicles",
        "Rarefaction",
        "Osseous destruction",
        "Edema",
        "Joint space narrowing",
        "Air fluid levels",
        "Mucosal thickening",
        "Aplastic",
        "Aplasia",
        "Pneumocephalus",
        "Calvarial lesions",
        "Sinusitis",
        "Mastoid opacity",
        "Abnormal calcifications",
        "Skull base asymmetry",
        "Air-fluid levels",
        "Craniotomy",
        "Post-surgical changes",
        "Dental artifacts",
        "Sutural diastasis",
        "Shunt tubing or valves",
        "Hypoplastic sinus",
        "Orbital emphysema",
        "Paranasal sinus expansion",
        "Middle ear effusion"
    ],
    "C-spine": [
        "Foreign body",
        "Fracture",
        "Degenerative changes",
        "Spondylolisthesis",
        "Scoliosis",
        "Vertebral height loss",
        "Osteophytes",
        "Bone lesions",
        "Osteomyelitis",
        "Spondylolysis",
        "Bony mineralization",
        "Support devices",
        "No findings",
        "Compression fracture",
        "Schmorl's node",
        "Intervertebral disc narrowing",
        "Ankylosis",
        "Vacuum disc phenomenon",
        "Spinal canal narrowing",
        "Hardware malposition or loosening",
        "Vertebral collapse",
        "Spinal deformity",
        "Postoperative fusion changes",
        "Enthesophytes",
        "Kyphosis",
        "Lordosis",
        "Lateral curvature",
        "Straightening",
        "Aortic calcifications",
        "Pseudoarticulation",
        "Spondylosis",
        "Soft tissue swelling",
        "Foreign bodies",
        "Epiglottitis",
        "Tracheal deviation",
        "Airway patency/narrowing",
        "Traumatic subluxation",
        "Listhesis",
        "Calcifications",
        "Prevertebral soft tissue widening",
        "Cervical spine alignment",
        "Retropharyngeal air",
        "Laryngeal fracture",
        "Cervical rib",
        "Atlantoaxial subluxation",
        "Odontoid fracture",
        "Prevertebral hematoma",
        "Subglottic narrowing",
        "Hyoid bone abnormality",
        "Thyroid enlargement",
        "Post-surgical air",
        "Hardware",
        "Carotid calcifications",
        "Soft tissue emphysema",
        "Calcific tendinitis of the longus colli muscle",
        "Pharyngeal soft tissue masses",
        "Esophageal dilation",
        "Tracheal stenosis",
        "Soft tissue air tracking from perforation",
        "Tracheostomy tube placement abnormalities",
        "Ossification of the posterior longitudinal ligament",
        "Hardware loosening",
        "Hardware malposition",
        "Uncovertebral joint arthrosis",
        "Facet joint hypertrophy or arthropathy",
        "Bilateral or unilateral facet joint ankylosis",
        "Atlanto-occipital joint abnormalities",
        "Neural foraminal narrowing",
        "Odontoid process sclerosis",
        "Odontoid process fragmentation",
        "Cervical rib variations",
        "Congenital fusion of cervical vertebrae (Klippel-Feil syndrome)"
    ],
    "T-spine": [
        "Fracture",
        "Degenerative changes",
        "Spondylolisthesis",
        "Scoliosis",
        "Vertebral height loss",
        "Osteophytes",
        "Bone lesions",
        "Osteomyelitis",
        "Spondylolysis",
        "Bony mineralization",
        "Support devices",
        "No findings",
        "Compression fracture",
        "Schmorl's node",
        "Intervertebral disc narrowing",
        "Ankylosis",
        "Vacuum disc phenomenon",
        "Spinal canal narrowing",
        "Hardware loosening",
        "Hardware malposition",
        "Vertebral collapse",
        "Spinal deformity",
        "Postoperative fusion changes",
        "Enthesophytes",
        "Kyphosis",
        "Lordosis",
        "Lateral curvature",
        "Straightening",
        "Aortic calcifications",
        "Pseudoarticulation",
        "Spondylosis",
        "Levoconvex",
        "Detroconvex",
        "Absent pedicle",
        "Hemivertebra",
        "Butterfly vertebra",
        "Block vertebrae",
        "Costovertebral joint arthropathy",
        "Ossification of the ligamentum flavum",
        "Sacralization",
        "Lumbarization",
        "Hemangioma",
        "Rib notching"
    ],
    "L-spine": [
        "Fracture",
        "Degenerative changes",
        "Spondylolisthesis",
        "Scoliosis",
        "Vertebral height loss",
        "Osteophytes",
        "Bone lesions",
        "Osteomyelitis",
        "Spondylolysis",
        "Bony mineralization",
        "Support devices",
        "No findings",
        "Compression fracture",
        "Schmorl's node",
        "Intervertebral disc narrowing",
        "Ankylosis",
        "Vacuum disc phenomenon",
        "Spinal canal narrowing",
        "Sacroiliitis",
        "Hardware malposition",
        "Hardware loosening",
        "Vertebral collapse",
        "Spinal deformity",
        "Postoperative fusion changes",
        "Enthesophytes",
        "Kyphosis",
        "Lordosis",
        "Lateral curvature",
        "Straightening",
        "Aortic calcifications",
        "Pseudoarticulation",
        "Spondylosis",
        "Facet joint arthropathy",
        "Transitional vertebrae",
        "Pars interarticularis defects",
        "Lumbar facet joint effusions",
        "Ossification of the posterior longitudinal ligament",
        "Spina bifida occulta",
        "Sacralization of L5",
        "Lumbarization of S1"
    ],
    "Chest": [
        "Adenopathy",
        "Airspace Opacity",
        "Aortic elongation/enlargement",
        "Arthritis",
        "Asthma",
        "Atelectasis",
        "Bronchitis",
        "Calcification",
        "Cardiomegaly",
        "Consolidation",
        "Congestive heart failure",
        "COVID-19",
        "Emphysema",
        "Enlarged mediastinum",
        "Enlarged pulmonary artery",
        "Fibrosis",
        "Fracture",
        "Granuloma",
        "Hernia",
        "Hyperinflation",
        "Mass/Nodule",
        "Mediastinal shift",
        "Osteoporosis",
        "Pericardial effusion",
        "Perihilar opacity",
        "Pleural effusion",
        "Pleural thickening",
        "Pneumonia",
        "Pneumonitis",
        "Pneumothorax",
        "Pulmonary cavity",
        "Sarcoidosis",
        "Scarring",
        "Spondylitis",
        "Tortuous aorta",
        "Tuberculosis",
        "Venous congestion",
        "Foreign bodies",
        "Support devices",
        "No findings",
        "Interstitial lung disease (ILD)",
        "Bronchiectasis",
        "Subcutaneous emphysema",
        "Lung volume loss",
        "Diaphragmatic eventration",
        "Diaphragmatic paralysis",
        "Pulmonary edema",
        "Chest wall mass",
        "Tracheal deviation",
        "Post-surgical changes",
        "Pacemaker leads",
        "Endotracheal tube malposition",
        "Nasogastric tube malposition",
        "Esophageal Dilation",
        "Degenerative changes",
        "Pneumomediastinum",
        "Pneumoperitoneum",
        "Diaphragmatic elevation",
        "Cardiac devices",
        "Pleural plaque",
        "Scoliosis",
        "Tracheostomy tube malposition",
        "Distended bowel",
        "Opacified hemithorax",
        "Lucent hemithorax",
        "Pulmonary cavitary lesion",
        "Enteric tube",
        "Overlying artifacts",
        "Air bronchogram",
        "Kerley B lines",
        "Hiatal hernia",
        "Calcified granuloma",
        "Chilaiditi sign",
        "Pulmonary alveolar proteinosis",
        "Costophrenic angle blunting",
        "Pulmonary contusion",
        "Pulmonary sequestration",
        "Cervical ribs",
        "Blastic lesions",
        "Lytic lesions",
        "Tracheal stenosis",
        "Flattening of the hemi diaphragm"
    ],
    "Abdomen": [
        "Bowel obstruction",
        "Free air",
        "Abnormal calcifications",
        "Foreign bodies",
        "Organomegaly",
        "Abnormal gas patterns",
        "Masses",
        "Ileus",
        "Ascites",
        "Constipation",
        "Support devices",
        "No findings",
        "Bowel dilation",
        "Pneumatosis intestinalis",
        "Portal venous gas",
        "Gallstones",
        "Renal stones",
        "Ureteral calculi",
        "Colonic distension",
        "Spinal calcifications",
        "Surgical clips or staples",
        "Uterine fibroids",
        "Medical devices",
        "Degenerative changes",
        "Stool",
        "Pneumotosis",
        "Air fluid levels",
        "IUD",
        "Pneumoperitoneum",
        "Heterotopic ossification",
        "Bowel wall thickening",
        "Diaphragmatic hernia",
        "Bladder distension or masses",
        "Ureteral stents",
        "Calcified phleboliths"
    ],
    "Pelvis": [
        "Fracture",
        "Dislocation",
        "Arthritis",
        "Bone lesions",
        "Avascular necrosis",
        "Asymmetry",
        "Joint effusion",
        "Soft tissue swelling",
        "Subcutaneous gas",
        "Soft tissue calcifications",
        "Osteomyelitis",
        "Bony mineralization",
        "Support devices",
        "No findings",
        "Pubic symphysis diastasis",
        "Soft tissue mass",
        "Intra-articular Body",
        "Pelvic phleboliths",
        "Urologic stent",
        "Ureteral calculi",
        "Degenerative changes",
        "Foley catheter",
        "Pelvic tilt",
        "Sacralization of spine",
        "Stool",
        "Constipation",
        "IUD",
        "Cam deformity",
        "Slipped capital femoral epiphysis",
        "Femoral acetabular impingement",
        "Subchondral cyst",
        "Protrusio acetabuli",
        "Osteochondral defects",
        "Heterotopic ossification",
        "Enthesopathy",
        "Synovial chondromatosis",
        "Acetabular retroversion sign",
        "Crossover sign",
        "Intra-articular Body",
        "Ankylosis",
        "Sacroiliitis",
        "Joint widening",
        "Osteitis condensans ilii",
        "Osteitis pubis",
        "Spina bifida occulta",
        "Pelvic vascular calcifications"
    ],
    "Arm": [
        "Fracture",
        "Dislocation",
        "Arthritic changes",
        "Joint effusion",
        "Soft tissue swelling",
        "Subcutaneous gas",
        "Foreign bodies",
        "Bone lesions",
        "Osteomyelitis",
        "Periosteal reaction",
        "Erosive change",
        "Bony mineralization",
        "Support devices",
        "No findings",
        "Amputation",
        "Joint subluxation",
        "Growth plate abnormalities",
        "Hardware complication",
        "Nonunion",
        "Malunion",
        "Tendinous calcifications",
        "Charcot joint",
        "Stress reaction",
        "Synostosis",
        "Degenerative changes",
        "Enthesophytes",
        "Osteophytes",
        "Ulnar variance",
        "Soft tissue calcifications",
        "Buckle fracture",
        "Scaphoid fracture",
        "Ossicles",
        "Rarefaction",
        "Osseous destruction",
        "Edema",
        "Joint space narrowing",
        "Synostosis between radius and ulna",
        "Myositis ossificans",
        "Bone infarcts",
        "Osteochondral defects",
        "Fat pad signs suggesting joint effusion",
        "Os subcoronoideum",
        "Os supratrochlear",
        "Bony Bankart",
        "Hill-Sachs",
        "Rotator cuff calcific tendinitis",
        "Acromioclavicular joint separation",
        "Os acromiale",
        "AC separation",
        "Distal clavicle osteolysis"
    ],
    "Hand": [
        "Fracture",
        "Dislocation",
        "Arthritic changes",
        "Joint effusion",
        "Soft tissue swelling",
        "Subcutaneous gas",
        "Foreign bodies",
        "Bone lesions",
        "Osteomyelitis",
        "Periosteal reaction",
        "Erosive change",
        "Bony mineralization",
        "Support devices",
        "No findings",
        "Amputation",
        "Joint subluxation",
        "Growth plate abnormalities",
        "Hardware complication",
        "Nonunion",
        "Malunion",
        "Tendinous calcifications",
        "Charcot joint",
        "Stress reaction",
        "Synostosis",
        "Degenerative changes",
        "Enthesophytes",
        "Osteophytes",
        "Ulnar variance",
        "Soft tissue calcifications",
        "Ossicles",
        "Rarefaction",
        "Osseous destruction",
        "Edema",
        "Joint space narrowing",
        "Boutonniere deformity",
        "Swan neck deformity",
        "Trigger finger deformity signs",
        "Carpal coalition",
        "Avascular necrosis",
        "Kienbock's disease",
        "Madelung deformity",
        "Acro-osteolysis",
        "Carpal boss",
        "Enostosis",
        "Ankylosis",
        "Jersey finger sign",
        "Collar button",
        "os interphalangeus",
        "acro-osteolysis",
        "Phalangeal osteolysis",
        "Joint ankylosis",
        "Synovial chondromatosis",
        "Tendon avulsion fractures",
        "Buckle fracture",
        "Scaphoid fracture",
        "Scaphoid avascular necrosis (Kienbock's disease)",
        "Bipartite pisiform",
        "Lunate dislocation",
        "Perilunate dislocation"
    ],
    "Leg": [
        "Fracture",
        "Dislocation",
        "Arthritic changes",
        "Joint effusion",
        "Soft tissue swelling",
        "Subcutaneous gas",
        "Foreign bodies",
        "Bone lesions",
        "Osteomyelitis",
        "Periosteal reaction",
        "Erosive change",
        "Bony mineralization",
        "Support devices",
        "No findings",
        "Amputation",
        "Joint subluxation",
        "Growth plate abnormalities",
        "Hardware complication",
        "Nonunion",
        "Malunion",
        "Tendinous calcifications",
        "Charcot joint",
        "Stress reaction",
        "Limb-length discrepancy",
        "Synostosis",
        "Degenerative changes",
        "Enthesophytes",
        "Osteophytes",
        "Soft tissue calcifications",
        "Ossicles",
        "Rarefaction",
        "Osseous destruction",
        "Edema",
        "Joint space narrowing",
        "Cam deformity",
        "FAI",
        "Femoral acetabular impingement",
        "Subchondral cyst",
        "Cortical thickening",
        "Bone infarcts",
        "Muscle atrophy",
        "Migration of hardware",
        "Loosening of hardware",
        "Heterotopic ossification",
        "Myositis ossificans",
        "Osteochondral defects",
        "Calcifications",
        "Meniscal calcifications",
        "Patellar tracking abnormalities",
        "Bipartite patella",
        "Osteochondritis dissecans",
        "Intra-articular bodies",
        "Osteochondral lesions"
    ],
    "Foot": [
        "Fracture",
        "Dislocation",
        "Arthritic changes",
        "Joint effusion",
        "Soft tissue swelling",
        "Subcutaneous gas",
        "Foreign bodies",
        "Bone lesions",
        "Osteomyelitis",
        "Periosteal reaction",
        "Erosive change",
        "Bony mineralization",
        "Support devices",
        "No findings",
        "Amputation",
        "Joint subluxation",
        "Growth plate abnormalities",
        "Hardware complication",
        "Nonunion",
        "Malunion",
        "Tendinous calcifications",
        "Charcot joint",
        "Stress reaction",
        "Synostosis",
        "Degenerative changes",
        "Enthesophytes",
        "Osteophytes",
        "Soft tissue calcifications",
        "Ossicles",
        "Rarefaction",
        "Osseous destruction",
        "Edema",
        "Joint space narrowing",
        "Osteochondral lesion",
        "Syndesmotic injury",
        "Tarsal coalition",
        "Os navicularis",
        "Os trigonum",
        "Kager's fat pad",
        "Hallux valgus",
        "Accessory ossicles",
        "Lisfranc",
        "Subchondral cysts",
        "Claw toe",
        "Hammer toe",
        "Bunionette deformity",
        "Tailor's bunion",
        "Acro-osteolysis",
        "Os interphalangeus"
    ]
}

