LABELS_BY_BODY_PART = {
    "Abdomen": [
        "Bowel obstruction",
        "Bowel dilation",
        "Colonic distension",
        "Air fluid levels",
        "Pneumoperitoneum",
        "Free air",
        "Calcifications",
        "Vascular calcifications in abdominal vessels",
        "Calcified phleboliths",
        "Heterotopic ossification",
        "Abnormal calcifications",
        "Foreign bodies",
        "Organomegaly",
        "Masses",
        "Ileus",
        "Abnormal gas patterns",
        "Ascites",
        "Stool",
        "Constipation",
        "Support devices",
        "Pneumatosis intestinalis",
        "Portal venous gas",
        "Gallstones",
        "Renal stones",
        "Ureteral calculi",
        "Medical devices",
        "Ureteral stents",
        "Surgical clips or staples",
        "Iud",
        "Uterine fibroids",
        "Degenerative changes",
        "Pneumatosis",
        "Bowel wall thickening",
        "Diaphragmatic hernia",
        "Bladder distension or masses",
        "No findings"
    ],
    "Arm": [
        "Fracture",
        "Scaphoid fracture",
        "Buckle fracture",
        "Bony bankart",
        "Hill sachs",
        "Dislocation",
        "Joint subluxation",
        "Acromioclavicular joint separation",
        "Ac separation",
        "Joint effusion",
        "Soft tissue swelling",
        "Subcutaneous gas",
        "Foreign bodies",
        "Bone lesions",
        "Osteomyelitis",
        "Periosteal reaction",
        "Edema",
        "Erosive change",
        "Rarefaction",
        "Osseous destruction",
        "Bony mineralization",
        "Amputation",
        "Growth plate abnormalities",
        "Hardware complication",
        "Malunion",
        "Nonunion",
        "Tendinous calcifications",
        "Charcot joint",
        "Synostosis",
        "Degenerative changes",
        "Enthesophytes",
        "Osteophytes",
        "Arthritic changes",
        "Joint space narrowing",
        "Ulnar variance",
        "Soft tissue calcifications",
        "Myositis ossificans",
        "Synostosis between radius and ulna",
        "Bone infarcts",
        "Fat pad signs suggesting joint effusion",
        "Os subcoronoideum",
        "Os supratrochlear",
        "Os acromiale",
        "Rotator cuff calcific tendinitis",
        "Distal clavicle osteolysis",
        "No findings"
    ],
    "C-spine": [
        "Foreign body",
        "Foreign bodies",
        "Fracture",
        "Vertebral height loss",
        "Compression fracture",
        "Vertebral collapse",
        "Odontoid fracture",
        "Hyoid bone fractures or dislocations",
        "Thyroid cartilage fractures",
        "Laryngeal fracture",
        "Degenerative changes",
        "Osteophytes",
        "Intervertebral disc narrowing",
        "Vacuum disc phenomenon",
        "Spondylosis",
        "Facet joint arthropathy",
        "Spinal canal narrowing",
        "Enthesophytes",
        "Uncovertebral joint arthrosis",
        "Neural foraminal narrowing",
        "Dislocation",
        "Traumatic subluxation",
        "Atlantoaxial subluxation",
        "Atlanto-occipital joint abnormalities",
        "Spondylolisthesis",
        "Listhesis",
        "Scoliosis",
        "Spondylolysis",
        "Bone lesions",
        "Osteomyelitis",
        "Bony mineralization",
        "Support devices",
        "Tracheostomy tube placement abnormalities",
        "Hardware",
        "Hardware malposition",
        "Hardware loosening",
        "Postoperative fusion changes",
        "Spinal deformity",
        "Pseudoarticulation",
        "Schmorls node",
        "Ankylosis",
        "Congenital fusion of cervical vertebrae (klippel-feil syndrome)",
        "Odontoid process sclerosis",
        "Odontoid process fragmentation",
        "Bilateral or unilateral facet joint ankylosis",
        "Tracheal stenosis",
        "Tracheal deviation",
        "Soft tissue swelling",
        "Epiglottitis",
        "Airway patency/narrowing",
        "Prevertebral soft tissue widening",
        "Subglottic narrowing",
        "Prevertebral hematoma",
        "Pharyngeal soft tissue masses",
        "Cervical rib",
        "Cervical rib variations",
        "Soft tissue emphysema",
        "Retropharyngeal air",
        "Post-surgical air",
        "Soft tissue air tracking from perforation",
        "Calcifications",
        "Aortic calcifications",
        "Carotid calcifications",
        "Ossification of the posterior longitudinal ligament",
        "Calcific tendinitis of the longus colli muscle",
        "Aortic calcifications",
        "Cervical spine alignment",
        "Kyphosis",
        "Lordosis",
        "Lateral curvature",
        "Straightening",
        "Hyoid bone abnormality",
        "Thyroid enlargement",
        "Esophageal dilation",
        "No findings"
    ],
    "Chest": [
        "Adenopathy",
        "Airspace opacity",
        "Consolidation",
        "Pneumonia",
        "Covid-19",
        "Pneumonitis",
        "Aortic enlargement",
        "Degenerative changes",
        "Arthritis",
        "Asthma",
        "Atelectasis",
        "Bronchitis",
        "Calcification",
        "Cardiomegaly",
        "Pericardial effusion",
        "Pulmonary contusion",
        "Congestive heart failure",
        "Pulmonary edema",
        "Kerley b lines",
        "Venous congestion",
        "Edema",
        "Air bronchogram",
        "Emphysema",
        "Hyperinflation",
        "Enlarged mediastinum",
        "Enlarged pulmonary artery",
        "Fibrosis",
        "Fracture",
        "Rib fracture",
        "Granuloma",
        "Calcified granuloma",
        "Hiatal hernia",
        "Hernia",
        "Pulmonary cavitary lesion",
        "Mass/nodule",
        "Mediastinal shift",
        "Osteoporosis",
        "Perihilar opacity",
        "Pleural effusion",
        "Costophrenic angle blunting",
        "Opacified hemithorax",
        "Pleural thickening",
        "Pneumothorax",
        "Lucent hemithorax",
        "Diaphragmatic elevation",
        "Diaphragmatic eventration",
        "Diaphragmatic paralysis",
        "Flattening of the hemi diaphragm",
        "Sarcoidosis",
        "Scarring",
        "Tortuous aorta",
        "Tuberculosis",
        "Pleural plaque",
        "Foreign bodies",
        "Support devices",
        "Endotracheal tube malposition",
        "Nasogastric tube malposition",
        "Tracheostomy tube malposition",
        "Enteric tube",
        "Cardiac devices",
        "Pacemaker leads",
        "Interstitial lung disease (ild)",
        "Bronchiectasis",
        "Subcutaneous emphysema",
        "Lung volume loss",
        "Bone lesion",
        "Lytic lesions",
        "Blastic lesions",
        "Spondlyitis",
        "Scoliosis",
        "Chest wall mass",
        "Tracheal deviation",
        "Post-surgical changes",
        "Tracheal stenosis",
        "Esophageal dilation",
        "Pneumomediastinum",
        "Pneumoperitoneum",
        "Cervical ribs",
        "Distended bowel",
        "No findings"
    ],
    "Foot": [
        "Fracture",
        "Malunion",
        "Osteochondral lesion",
        "Stress fracture",
        "Avulsion fractures",
        "Dislocation",
        "Joint subluxation",
        "Lisfranc",
        "Claw toe",
        "Hammer toe",
        "Arthritic changes",
        "Joint effusion",
        "Soft tissue swelling",
        "Edema",
        "Subcutaneous gas",
        "Foreign bodies",
        "Bone lesions",
        "Osteomyelitis",
        "Periosteal reaction",
        "Degenerative changes",
        "Joint space narrowing",
        "Subchondral cysts",
        "Erosive change",
        "Osseous destruction",
        "Bony mineralization",
        "Charcot joint",
        "Amputation",
        "Tarsal coalition",
        "Growth plate abnormalities",
        "Hardware complication",
        "Syndesmotic injury",
        "Kagers fat pad",
        "Nonunion",
        "Tendinous calcifications",
        "Hallux valgus",
        "Synostosis",
        "Soft tissue calcifications",
        "Ossicles",
        "Accessory ossicles",
        "Os navicularis",
        "Os trigonum",
        "Os interphalangeus",
        "Rarefaction",
        "No findings"
    ],
    "Hand": [
        "Fracture",
        "Tuft fractures",
        "Buckle fracture",
        "Scaphoid fracture",
        "Tendon avulsion fractures",
        "Dislocation",
        "Joint subluxation",
        "Lunate dislocation",
        "Perilunate dislocation",
        "Soft tissue swelling",
        "Subcutaneous gas",
        "Foreign bodies",
        "Bone lesions",
        "Osteomyelitis",
        "Periosteal reaction",
        "Erosive change",
        "Rarefaction",
        "Osseous destruction",
        "Phalangeal osteolysis",
        "Bony mineralization",
        "Amputation",
        "Hardware",
        "Hardware complication",
        "Malunion",
        "Nonunion",
        "Tendinous calcifications",
        "Soft tissue calcifications",
        "Charcot joint",
        "Synostosis",
        "Degenerative changes",
        "Enthesophytes",
        "Osteophytes",
        "Arthritic changes",
        "Joint space narrowing",
        "Ulnar variance",
        "Ossicles",
        "Os interphalangeus",
        "Edema",
        "Boutonniere deformity",
        "Swan neck deformity",
        "Trigger finger deformity signs",
        "Madelung deformity",
        "Carpal coalition",
        "Avascular necrosis",
        "Acro-osteolysis",
        "Carpal boss",
        "Enostosis",
        "Acro-osteolysis",
        "Scaphoid avascular necrosis (kienbocks disease)",
        "No findings"
    ],
    "Head": [
        "Fracture",
        "Pathological fracture",
        "Nonunion",
        "Malunion",
        "Dislocation",
        "Joint subluxation",
        "Soft tissue swelling",
        "Orbital emphysema",
        "Subcutaneous gas",
        "Foreign bodies",
        "Metallic foreign body",
        "Intracranial foreign body",
        "Dental artifacts",
        "Periosteal reaction",
        "Osteomyelitis",
        "Erosive change",
        "Bony mineralization",
        "Support devices",
        "Hardware complication",
        "Shunt tubing or valves",
        "Degenerative changes",
        "Arthritic changes",
        "Joint space narrowing",
        "Pneumocephalus",
        "Calvarial lesions",
        "Aplastic",
        "Aplasia",
        "Osseous destruction",
        "Bone lesions",
        "Skull base asymmetry",
        "Sutural diastasis",
        "Hypoplastic sinus",
        "Paranasal sinus expansion",
        "Soft tissue calcifications",
        "Abnormal calcifications",
        "Sinusitis",
        "Air-fluid levels",
        "Mucosal thickening",
        "Mastoid opacity",
        "Middle ear effusion",
        "Post-surgical changes",
        "Craniotomy",
        "Rarefaction",
        "No findings"
    ],
    "L-spine": [
        "Fracture",
        "Vertebral height loss",
        "Compression fracture",
        "Vertebral collapse",
        "Degenerative changes",
        "Osteophytes",
        "Intervertebral disc narrowing",
        "Vacuum disc phenomenon",
        "Spondylosis",
        "Facet joint arthropathy",
        "Spinal canal narrowing",
        "Enthesophytes",
        "Spondylolisthesis",
        "Scoliosis",
        "Lateral curvature",
        "Scoliosis with rotational deformities",
        "Hardware",
        "Hardware malposition",
        "Hardware loosening",
        "Postoperative fusion changes",
        "Support devices",
        "Bone lesions",
        "Osteomyelitis",
        "Bony mineralization",
        "Sacroiliitis",
        "Spinal deformity",
        "Pseudoarticulation",
        "Schmorls node",
        "Ankylosis",
        "Spina bifida occulta",
        "Sacralization of l5",
        "Lumbarization of s1",
        "Transitional vertebrae",
        "Transitional sacral vertebrae anomalies",
        "Pars interarticularis defects",
        "Spondylolysis",
        "Calcification",
        "Aortic calcifications",
        "Ossification of the posterior longitudinal ligament",
        "Iliolumbar ligament calcifications or ossifications",
        "Calcification of interspinous ligaments",
        "Straightening",
        "Kyphosis",
        "Lordosis",
        "No findings"
    ],
    "Leg": [
        "Fracture",
        "Stress reaction",
        "Malunion",
        "Nonunion",
        "Stress fracture callus formation",
        "Dislocation",
        "Joint subluxation",
        "Degenerative changes",
        "Enthesophytes",
        "Osteophytes",
        "Subchondral cyst",
        "Arthritic changes",
        "Osteochondral defects",
        "Joint space narrowing",
        "Joint effusion",
        "Soft tissue swelling",
        "Edema",
        "Subcutaneous gas",
        "Foreign bodies",
        "Bone lesions",
        "Osteomyelitis",
        "Periosteal reaction",
        "Erosive change",
        "Rarefaction",
        "Osseous destruction",
        "Bony mineralization",
        "Hardware",
        "Hardware complication",
        "Loosening of hardware",
        "Migration of hardware",
        "Amputation",
        "Growth plate abnormalities",
        "Tendinous calcifications",
        "Soft tissue calcifications",
        "Charcot joint",
        "Limb-length discrepancy",
        "Synostosis",
        "Femoral acetabular impingement",
        "Fai",
        "Cam deformity",
        "Cortical thickening",
        "Bone infarcts",
        "Heterotopic ossification",
        "Myositis ossificans",
        "Calcifications",
        "Meniscal calcifications",
        "Patellar tracking abnormalities",
        "Bipartite patella",
        "Osteochondritis dissecans",
        "Intraarticular bodies",
        "Osteochondral lesions",
        "No findings"
    ],
    "Pelvis": [
        "Fracture",
        "Dislocation",
        "Joint widening",
        "Pubic symphysis diastasis",
        "Bone lesions",
        "Avascular necrosis",
        "Soft tissue swelling",
        "Subcutaneous gas",
        "Osteomyelitis",
        "Bony mineralization",
        "Medical devices",
        "Urologic stent",
        "Foley catheter",
        "Iud",
        "Soft tissue mass",
        "Intra-articular body",
        "Ureteral calculi",
        "Degenerative changes",
        "Enthesopathy",
        "Arthritis",
        "Subchondral cyst",
        "Sacralization of spine",
        "Stool",
        "Constipation",
        "Cam deformity",
        "Slipped capital femoral epiphysis",
        "Femoral acetabular impingement",
        "Protrusio acetabuli",
        "Osteochondral defects",
        "Heterotopic ossification",
        "Soft tissue calcifications",
        "Acetabular retroversion sign",
        "Crossover sign",
        "Sacroiliitis",
        "Osteitis condensans ilii",
        "Osteitis pubis",
        "Pelvic vascular calcifications",
        "Pelvic phleboliths",
        "No findings"
    ],
    "T-spine": [
        "Fracture",
        "Vertebral height loss",
        "Compression fracture",
        "Vertebral collapse",
        "Rib head fractures or dislocations",
        "Degenerative changes",
        "Osteophytes",
        "Intervertebral disc narrowing",
        "Vacuum disc phenomenon",
        "Spondylosis",
        "Facet joint arthropathy",
        "Spinal canal narrowing",
        "Enthesophytes",
        "Costovertebral joint arthropathy",
        "Spondylolisthesis",
        "Bone lesions",
        "Absent pedicle",
        "Osteomyelitis",
        "Spondylolysis",
        "Bony mineralization",
        "Support devices",
        "Straightening",
        "Kyphosis",
        "Lordosis",
        "Spinal deformity",
        "Pseudoarticulation",
        "Schmorls node",
        "Ankylosis",
        "Spina bifida occulta",
        "Butterfly vertebra",
        "Hemivertebra",
        "Block vertebrae",
        "Pars interarticularis defects",
        "Spondylolysis",
        "Hardware",
        "Hardware malposition",
        "Hardware loosening",
        "Postoperative fusion changes",
        "Scoliosis",
        "Lateral curvature",
        "Scoliosis with rotational deformities",
        "Levoconvex",
        "Dextroconvex",
        "Calcification",
        "Aortic calcifications",
        "Ossification of the posterior longitudinal ligament",
        "Calcification of interspinous ligaments",
        "Ossification of the ligamentum flavum",
        "Rib notching",
        "Costotransverse joint abnormalities",
        "No findings"
    ]
}
