[project]
name = "epsml"
version = "0.1.0"
description = "Epsilon ML monorepo"
requires-python = "==3.10.12"

[tool.uv.workspace]
members = [
    "packages/*",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
