[project]
name = "epscloudapi"
version = "0.1.0"
description = "Cloud storage utilities for AWS S3 and GCS"
requires-python = "==3.10.12"
dependencies = [
    "boto3>=1.38.36",
    "google-cloud-storage>=3.1.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/epscloudapi"]
