general:
  experiment_name: "v1.3.0"
  run_name: ""
  notes: ""
  save_full_model: False

paths:
  intern_vl_checkpoint_dir: "/mnt/training/internvl_weights/internvl3_chimera_20250810_083849_1e-5_0810_no_label_gpt_bodypart/checkpoint-10466"
  train_file: "/mnt/training/splits/gradient_batches_1-6_segmed_batches_1-16_simonmed_batches_1-10/CONSOLIDATED_gradient_batches_1-6_segmed_batches_1-16_simonmed_batches_1-10_reports_with_labels_train.csv"
  validation_file: "/mnt/training/splits/gradient_batches_1-6_segmed_batches_1-16_simonmed_batches_1-10/CONSOLIDATED_gradient_batches_1-6_segmed_batches_1-16_simonmed_batches_1-10_reports_with_labels_val.csv"
  test_file: "/mnt/training/splits/gradient_batches_1-6_segmed_batches_1-16_simonmed_batches_1-10/CONSOLIDATED_gradient_batches_1-6_segmed_batches_1-16_simonmed_batches_1-10_reports_with_labels_test.csv"
  base_path_substitutions:
    "gradient_22JUL2024": "/mnt/all-data/sfs-gradient-chest/22JUL2024"
    "gradient_20DEC2024": "/mnt/all-data/sfs-gradient-chest/20DEC2024"
    "gradient_09JAN2025": "/mnt/all-data/sfs-gradient-chest/09JAN2025"
    "gradient_16AUG2024": "/mnt/all-data/sfs-gradient-nochest/16AUG2024"
    "gradient_13JAN2025": "/mnt/all-data/sfs-gradient-nochest/13JAN2025/deid"
    "gradient_01JUL2025":  /mnt/all-data/sfs-gradient-new/01JUL2025
    "segmed_batch_1": "/mnt/all-data/sfs-segmed-1"
    "segmed_batch_2": "/mnt/all-data/sfs-segmed-2"
    "segmed_batch_3": "/mnt/all-data/sfs-segmed-34/segmed_3"
    "segmed_batch_4": "/mnt/all-data/sfs-segmed-34/segmed_4"
    "segmed_batch_5": "/mnt/all-data/sfs-segmed567/segmed_5"
    "segmed_batch_6": "/mnt/all-data/sfs-segmed567/segmed_6"
    "segmed_batch_7": "/mnt/all-data/sfs-segmed567/segmed_7"
    "segmed_batch_8": "/mnt/all-data/sfs-segmed89/batch8"
    "segmed_batch_9": "/mnt/all-data/sfs-segmed89/batch9"
    "segmed_batch_10": "/mnt/all-data/sfs-segmed10"
    "segmed_batch_11": "/mnt/all-data/sfs-segmed11"
    "segmed_batch_12": "/mnt/all-data/sfs-segmed12"
    "segmed_batch_13": "/mnt/all-data/sfs-segmed13"
    "segmed_batch_14": "/mnt/all-data/sfs-segmed14"
    "segmed_batch_15": "/mnt/all-data/sfs-segmed15"
    "segmed_batch_16": "/mnt/all-data/sfs-segmed16"
    "simonmed": "/mnt/all-data/sfs-simonmed"
  output_dir: "/mnt/training/checkpoints/v1.3.0"

data:
  body_part: ""
  custom_labels: []
  treat_uncertain_as_positive: True
  perform_label_balancing: True
  negative_body_parts_ratio: 0.05
  compute_num_data_augmentations: True
  data_augmentation_target: 10000
  data_augmentation_min: 1000
  max_study_images: 8
  replace_dicom_with_png: False

training:
  perform_intra_epoch_validation: True
  intra_epoch_validation_step: 3000
  send_wandb_notification: False
  device: "cuda"
  device_ids: None
  num_training_workers_per_gpu: 32
  num_validation_workers_per_gpu: 32
  learning_rate: 0.01
  warmup_ratio: 0.05
  num_epochs: 2
  training_batch_size: 128
  validation_batch_size: 32
  min_allowed_batch_size: 2
  multi_image_input: True
  num_multi_images: None
  use_attentional_pooling: True
