general:
  model_name: dino_v3_classifier
  dataset_name: ""
  run_name: ""
  notes: ""
  custom_labels: []
  body_part: ""
  treat_uncertain_as_positive: true
  perform_label_balancing: true
  num_data_augmentations: 0
  compute_num_data_augmentations: false
  data_augmentation_target: 10000
  data_augmentation_min: 2000
  unroll_images: false
  use_report_text: false
  save_full_model: false
  replace_dicom_with_png: true
  dino_v3_type: large  # Options: small, base, large, giant
  dino_v3_output_dim: 1024  # 384 for small, 768 for base, 1024 for large, 4096 for giant (7B)
  dino_v3_img_size: 512
  use_attention_pooling: true

paths:
  dino_v3_checkpoint_path: ""
  train_file: /mnt/all-data/files/classifier_csvs/gradient_batches_1-5_segmed_batches_1-9_simonmed_batches_1-10_reports_with_labels_train_merged_filtered_consolidated_standardized_with_uncertain_labels.csv
  validation_file: /mnt/all-data/files/classifier_csvs/gradient_batches_1-5_segmed_batches_1-9_simonmed_batches_1-10_reports_with_labels_val_merged_filtered_consolidated_standardized_with_uncertain_labels.csv
  test_file: /mnt/all-data/files/classifier_csvs/gradient_batches_1-5_segmed_batches_1-9_simonmed_batches_1-10_reports_with_labels_test_merged_filtered_consolidated_standardized_with_uncertain_labels.csv
  base_path_substitutions:
    gradient/22JUL2024: /mnt/all-data/png/512x512/gradient/22JUL2024
    gradient/20DEC2024: /mnt/all-data/png/512x512/gradient/20DEC2024
    gradient/09JAN2025: /mnt/all-data/png/512x512/gradient/09JAN2025
    gradient/16AUG2024: /mnt/all-data/png/512x512/gradient/16AUG2024
    gradient/13JAN2025: /mnt/all-data/png/512x512/gradient/13JAN2025/deid
    segmed/batch1: /mnt/all-data/png/512x512/segmed/batch1
    segmed/batch2: /mnt/all-data/png/512x512/segmed/batch2
    segmed/batch3: /mnt/all-data/png/512x512/segmed/batch3
    segmed/batch4: /mnt/all-data/png/512x512/segmed/batch4
    segmed/batch5: /mnt/all-data/png/512x512/segmed/batch5
    segmed/batch6: /mnt/all-data/png/512x512/segmed/batch6
    segmed/batch7: /mnt/all-data/png/512x512/segmed/batch7
    segmed/batch8: /mnt/all-data/png/512x512/segmed/batch8
    segmed/batch9: /mnt/all-data/png/512x512/segmed/batch9
    segmed/batch10: /mnt/all-data/png/512x512/segmed/batch10
    simonmed: /mnt/all-data/png/512x512/simonmed
  output_dir: ./output

training:
  perform_intra_epoch_validation: false
  intra_epoch_validation_step: 5000
  send_wandb_notification: false
  device: cuda
  device_ids: None  # None for single GPU, or list like [0, 1, 2, 3] for multi-GPU
  num_training_workers_per_gpu: 8
  num_validation_workers_per_gpu: 8
  learning_rate: 0.00004
  warmup_ratio: 0.1
  num_epochs: 10
  training_batch_size: 256
  validation_batch_size: 256
  min_allowed_batch_size: 1
  multi_image_input: true
  max_multi_images: 8

