general:
  model_name: dino_v3_classifier
  dataset_name: sample_dataset
  run_name: DINOv3 – abdomen - degenerative changes
  notes: Training DINOv3 classifier on abdomen - degenerative changes
  custom_labels:
  - Degenerative changes
  body_part: Abdomen
  treat_uncertain_as_positive: true
  perform_label_balancing: true
  num_data_augmentations: 0
  compute_num_data_augmentations: false
  data_augmentation_target: 10000
  data_augmentation_min: 2000
  unroll_images: true
  use_report_text: false
  save_full_model: false
  dino_v3_type: large  # Options: small, base, large, giant
  dino_v3_output_dim: 1024  # 384 for small, 768 for base, 1024 for large, 4096 for giant (7B)

paths:
  dino_v3_checkpoint_path: /mnt/all-data/files/output_vitl_xray_highres/eval/training_11964/teacher_checkpoint.pth
  train_file: /home/yan/work/gradient_batches_1-5_segmed_batches_1-9_simonmed_batches_1-10_reports_with_labels_train_merged_filtered_consolidated_standardized_with_uncertain_labels.csv 
  validation_file: /home/yan/work/gradient_batches_1-5_segmed_batches_1-9_simonmed_batches_1-10_reports_with_labels_val_merged_filtered_consolidated_standardized_with_uncertain_labels.csv 
  test_file: /home/yan/work/gradient_batches_1-5_segmed_batches_1-9_simonmed_batches_1-10_reports_with_labels_test_merged_filtered_consolidated_standardized_with_uncertain_labels.csv 
  base_path_substitutions:
    gradient/22JUL2024: null
    gradient/20DEC2024: null
    gradient/09JAN2025: null
    gradient/16AUG2024: /mnt/all-data/sfs-gradient-nochest/16AUG2024/
    gradient/13JAN2025: /mnt/all-data/sfs-gradient-nochest/13JAN2025/deid
    segmed/batch1: /mnt/all-data/sfs-segmed-1
    segmed/batch2: /mnt/all-data/sfs-segmed-2
    segmed/batch3: /mnt/all-data/sfs-segmed-34/segmed_3
    segmed/batch4: /mnt/all-data/sfs-segmed-34/segmed_4
    segmed/batch5: /mnt/all-data/sfs-segmed567/segmed_5
    segmed/batch6: /mnt/all-data/sfs-segmed567/segmed_6
    segmed/batch7: /mnt/all-data/sfs-segmed567/segmed_7
    segmed/batch8: /mnt/all-data/sfs-segmed89/batch8
    segmed/batch9: /mnt/all-data/sfs-segmed89/batch9
    segmed/batch10: /mnt/all-data/sfs-segmed-10
    simonmed: /mnt/all-data/sfs-simonmed
  output_dir: ./output

training:
  perform_intra_epoch_validation: true
  intra_epoch_validation_step: 5000
  send_wandb_notification: false
  device: cuda
  device_ids: None  # None for single GPU, or list like [0, 1, 2, 3] for multi-GPU
  num_training_workers_per_gpu: 8
  num_validation_workers_per_gpu: 8
  learning_rate: 0.0002
  warmup_ratio: 0.1
  num_epochs: 3
  training_batch_size: 8
  validation_batch_size: 8
  min_allowed_batch_size: 2  # Minimum 2 for batch norm in classifier
  multi_image_input: false
  num_multi_images: None
