[project]
name = "epscore"
version = "0.1.0"
description = "Core utility functions for Epsilon ML"
requires-python = "==3.10.12"
dependencies = [
    "matplotlib>=3.10.1",
    "numpy>=1.26.4",
    "pandas>=2.2.3",
    "scipy>=1.15.2",
    "tqdm>=4.67.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/epscore"]
