[project]
name = "epsllmapi"
version = "0.1.0"
description = "LLM API utilities for GPT and Llama models"
requires-python = "==3.10.12"
dependencies = [
    "epscore",
    "openai>=1.95.1",
    "torch==2.5.1",
    "transformers==4.49.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/epsllmapi"]

[tool.uv.sources]
epscore = { workspace = true }
