[project]
name = "epsimaging"
version = "0.1.0"
description = "Medical imaging utilities for DICOM, NIFTI, and image processing"
requires-python = "==3.10.12"
dependencies = [
    "dicom2nifti>=2.5.1",
    "google-cloud-storage>=3.1.0",
    "numpy>=1.26.4",
    "pillow>=11.1.0",
    "pydicom>=3.0.1",
    "python-dateutil>=2.9.0.post0",
    "scipy>=1.15.2",
    "SimpleITK>=2.4.1",
    "tqdm>=4.67.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/epsimaging"]
