general:
  model_name: "intern_vit_classifier"
  dataset_name: "mimic_two_all_labels"
  run_name: "Chimera (Mimic without text training and validation)"
  notes: "Chimera, Mimic without text training and validation, loss=SampleBalancedBCEWithLogitsLoss"
  custom_labels:
  [
    "Atelectasis",
    "Cardiomegaly",
    "Consolidation",
    "Edema",
    "Enlarged Cardiomediastinum",
    "Fracture",
    "Lung Lesion",
    "Lung Opacity",
    "No Finding",
    "Pleural Effusion",
    "Pleural Other",
    "Pneumonia",
    "Pneumothorax",
    "Support Devices"
  ]
  do_cropping: False
  use_report_text: False
  save_full_model: False

paths:
  intern_vl_checkpoint_dir: "/mnt/efs/models/internvl/old/internvl2.5_26b_finetune_lora_20241229_184000_1e-5_2.5_gradient_full_rm_sole_no_findings_rm_bad_dcm_no_label/checkpoint-58670"
  gcs_train_file: "gs://aikica/mimic/mimic-all-labels-training-rui-split.jsonl"
  gcs_validation_file: "gs://aikica/mimic/mimic-all-labels-validation-rui-split.jsonl"
  gcs_extra_filtering_file: None
  images_dir: "/mnt/efs/all-cxr/mimic2-jpg/mimic-cxr-jpg-2.1.0.physionet.org"
  dir_prefix_to_remove: None
  remove_deid: False
  output_dir: "./output"

training:
  perform_intra_epoch_validation: True
  intra_epoch_validation_step: 1000
  send_wandb_notification: False
  device: "cuda"
  device_ids: None  # Use one (the default) GPU.
  # device_ids: [0, 1, 2, 3, 4, 5, 6, 7]  # Use 8 GPUs.
  num_training_workers_per_gpu: 8
  num_validation_workers_per_gpu: 8
  learning_rate:  0.01
  warmup_ratio: 0.05  # = 1/20
  num_epochs: 4
  training_batch_size: 32
  validation_batch_size: 32
  min_allowed_batch_size: 2  # In order for batch norm in the InternVitClassifier model to work.
  multi_image_input: False
  num_multi_images: None
