[project]
name = "intern-vit"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.10.12,<3.11"
dependencies = [
    "torch (>=2,<3)",
]

[tool.poetry.group.local.dependencies]
    internvl-chat = { git = "git@github.com/EpsilonLabsInc/InternVL-3x.git", tag = "v2.0.0-classifier.1", subdirectory = "internvl_chat" }

[tool.poetry.group.test.dependencies]
    utils-ml-inference = { git = "git@github.com/EpsilonLabsInc/utils_ml_inference.git", tag = "v5.0.1" }

[tool.poetry]
packages = [{include = "*", to = "intern_vit"}]
exclude = ["samples/*", "run_test.py"]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
