general:
  model_name: dino_v3_classifier
  dataset_name: c-spine_schmorls_node
  run_name: 005_015_032_768
  notes: ''
  custom_labels:
  - Schmorls node
  body_part: C-spine
  treat_uncertain_as_positive: true
  perform_label_balancing: true
  num_data_augmentations: 0
  compute_num_data_augmentations: false
  data_augmentation_target: 10000
  data_augmentation_min: 2000
  unroll_images: false
  use_report_text: false
  save_full_model: false
  replace_dicom_with_png: true
  dino_v3_type: large
  dino_v3_output_dim: 1024
  dino_v3_img_size: 768
  use_attention_pooling: true
paths:
  dino_v3_checkpoint_path: /mnt/all-data/files/output_vitl_xray_20_ep_005_015_032_768/eval/training_78559/teacher_checkpoint.pth
  train_file: /mnt/all-data/files/classifier_csvs/gradient_batches_1-5_segmed_batches_1-9_simonmed_batches_1-10_reports_with_labels_train_merged_filtered_consolidated_standardized_with_uncertain_labels.csv
  validation_file: /mnt/all-data/files/classifier_csvs/gradient_batches_1-5_segmed_batches_1-9_simonmed_batches_1-10_reports_with_labels_val_merged_filtered_consolidated_standardized_with_uncertain_labels.csv
  test_file: /mnt/all-data/files/classifier_csvs/gradient_batches_1-5_segmed_batches_1-9_simonmed_batches_1-10_reports_with_labels_test_merged_filtered_consolidated_standardized_with_uncertain_labels.csv
  base_path_substitutions:
    gradient/22JUL2024: null
    gradient/20DEC2024: null
    gradient/09JAN2025: null
    gradient/16AUG2024: /mnt/all-data/png/org-size/gradient/16AUG2024
    gradient/13JAN2025: /mnt/all-data/png/org-size/gradient/13JAN2025/deid
    segmed/batch1: /mnt/all-data/png/org-size/segmed/batch1
    segmed/batch2: /mnt/all-data/png/org-size/segmed/batch2
    segmed/batch3: /mnt/all-data/png/org-size/segmed/batch3
    segmed/batch4: /mnt/all-data/png/org-size/segmed/batch4
    segmed/batch5: /mnt/all-data/png/org-size/segmed/batch5
    segmed/batch6: /mnt/all-data/png/org-size/segmed/batch6
    segmed/batch7: /mnt/all-data/png/org-size/segmed/batch7
    segmed/batch8: /mnt/all-data/png/org-size/segmed/batch8
    segmed/batch9: /mnt/all-data/png/org-size/segmed/batch9
    segmed/batch10: /mnt/all-data/png/org-size/segmed/batch10
    simonmed: /mnt/all-data/png/org-size/simonmed
  output_dir: ./output
training:
  perform_intra_epoch_validation: false
  intra_epoch_validation_step: 5000
  send_wandb_notification: false
  device: cuda
  device_ids: None
  num_training_workers_per_gpu: 8
  num_validation_workers_per_gpu: 8
  learning_rate: 4.0e-05
  warmup_ratio: 0.1
  num_epochs: 4
  training_batch_size: 128
  validation_batch_size: 128
  min_allowed_batch_size: 1
  multi_image_input: true
  max_multi_images: 8
