[project]
name = "epssegmentors"
version = "0.1.0"
description = "Segmentation models for medical imaging"
requires-python = "==3.10.12"
dependencies = [
    "epsimaging",
    "monai>=1.4.0",
    "numpy>=1.26.4",
    "opencv-python>=4.11.0.86",
    "pillow>=11.1.0",
    "pydicom>=3.0.1",
    "requests",
    "torch==2.5.1",
    "torchvision==0.20.1",
    "torchxrayvision>=1.3.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/epssegmentors"]

[tool.uv.sources]
epsimaging = { workspace = true }
