[project]
name = "3d_image_encoders"
version = "0.1.0"
description = "3D image encoder models (Swin3D, MViT, I3D, X3D)"
requires-python = "==3.10.12"
dependencies = [
    "epsdatasets",
    "epstraining",
    "matplotlib>=3.10.1",
    "numpy>=1.26.4",
    "pandas>=2.2.3",
    "scikit-learn>=1.6.1",
    "SimpleITK>=2.4.1",
    "torch==2.5.1",
    "torchvision==0.20.1",
    "tqdm>=4.67.1",
    "wandb>=0.19.8",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/3d_image_encoders"]

[tool.uv.sources]
epsdatasets = { workspace = true }
epstraining = { workspace = true }
