from epsutils.labels.label_versions import v0_1_0, v1_0_0, v2_0_0

# v0.1.0 label maps.
V0_1_0_LABELS_BY_BODY_PART = v0_1_0.LABELS_BY_BODY_PART

# v1.0.0 label maps.
V1_0_0_LABELS_BY_BODY_PART = v1_0_0.LABELS_BY_BODY_PART

# v2.0.0 label maps.
V2_0_0_FINEGRAINED_LABELS_BY_BODY_PART = v2_0_0.FINEGRAINED_LABELS_BY_BODY_PART
V2_0_0_CONSOLIDATED_LABELS_BY_BODY_PART = v2_0_0.CONSOLIDATED_LABELS_BY_BODY_PART
V2_0_0_FINEGRAINED_TO_CONSOLIDATED_BY_BODY_PART = (
    v2_0_0.FINEGRAINED_TO_CONSOLIDATED_BY_BODY_PART
)
V2_0_0_CONSOLIDATED_TO_FINEGRAINED_BY_BODY_PART = (
    v2_0_0.CONSOLIDATED_TO_FINEGRAINED_BY_BODY_PART
)


# Current default label map.
LABELS_BY_BODY_PART = V2_0_0_FINEGRAINED_LABELS_BY_BODY_PART  # For backward compatibility.
FINEGRAINED_LABELS_BY_BODY_PART = V2_0_0_FINEGRAINED_LABELS_BY_BODY_PART
CONSOLIDATED_LABELS_BY_BODY_PART = V2_0_0_CONSOLIDATED_LABELS_BY_BODY_PART
