[project]
name = "epslabels"
version = "0.1.0"
description = "Label definitions and utilities for medical imaging"
requires-python = "==3.10.12"
dependencies = [
    "pandas>=2.2.3",
    "tqdm>=4.67.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/epslabels"]
