[project]
name = "epsclassifiers"
version = "0.1.0"
description = "Classification models for medical imaging"
requires-python = "==3.11.13"
dependencies = [
    "2d_image_encoders",
    "epscloudapi",
    "epsdatasets",
    "epsimaging",
    "epslabels",
    "epsllmapi",
    "epstraining",
    "einops==0.8.1",
    "numpy==2.3.3",
    "opencv-python==4.11.0.86",
    "pandas==2.3.2",
    "peft==0.17.1",
    "pillow==11.3.0",
    "pydicom==3.0.1",
    "PyYAML==6.0.2",
    "timm==1.0.20",
    "torch==2.5.1",
    "torchvision==0.20.1",
    "torchxrayvision==1.4.0",
    "tqdm==4.67.1",
    "transformers==4.49.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/epsclassifiers"]

[tool.uv.sources]
torch = [
    { index = "pytorch-cpu", marker = "sys_platform != 'linux'" },
    { index = "pytorch-cu121", marker = "sys_platform == 'linux'" },
]
torchvision = [
    { index = "pytorch-cpu", marker = "sys_platform != 'linux'" },
    { index = "pytorch-cu121", marker = "sys_platform == 'linux'" },
]
2d_image_encoders = { workspace = true }
epscloudapi = { workspace = true }
epsdatasets = { workspace = true }
epsimaging = { workspace = true }
epslabels = { workspace = true }
epsllmapi = { workspace = true }
epstraining = { workspace = true }
