[project]
name = "2d_image_encoders"
version = "0.1.0"
description = "2D image encoder models (InternVIT, DINOv3)"
requires-python = "==3.11.13"
dependencies = [
    "epsimaging",
    "dinov3",
    "internvl-chat",
    "einops==0.8.1",
    "peft==0.17.1",
    "pillow==11.3.0",
    "timm==1.0.20",
    "torch==2.5.1",
    "transformers==4.49.0",
    "xformers==0.0.29.post1; sys_platform == 'linux'",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/2d_image_encoders"]

[tool.uv.sources]
torch = [
    { index = "pytorch-cpu", marker = "sys_platform != 'linux'" },
    { index = "pytorch-cu121", marker = "sys_platform == 'linux'" },
]
epsimaging = { workspace = true }
dinov3 = { git = "ssh://git@github.com/EpsilonLabsInc/dinov3", branch = "xray-data" }
internvl-chat = { git = "ssh://git@github.com/EpsilonLabsInc/InternVL-3x", subdirectory = "internvl_chat", tag = "v2.0.0-classifier.2" }
