[project]
name = "epsdatasets"
version = "0.1.0"
description = "Dataset helpers for medical imaging datasets"
requires-python = "==3.11.13"
dependencies = [
    "epscloudapi",
    "epsimaging",
    "epslabels",
    "datasets==4.1.1",
    "huggingface-hub==0.35.1",
    "natsort==8.4.0",
    "nibabel==5.3.2",
    "numpy==2.3.3",
    "pandas==2.3.2",
    "pillow==11.3.0",
    "scikit-learn==1.7.2",
    "SimpleITK==2.5.2",
    "torch==2.5.1",
    "tqdm==4.67.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/epsdatasets"]

[tool.uv.sources]
torch = [
    { index = "pytorch-cpu", marker = "sys_platform != 'linux'" },
    { index = "pytorch-cu121", marker = "sys_platform == 'linux'" },
]
epscloudapi = { workspace = true }
epsimaging = { workspace = true }
epslabels = { workspace = true }
