[project]
name = "epsdatasets"
version = "0.1.0"
description = "Dataset helpers for medical imaging datasets"
requires-python = "==3.10.12"
dependencies = [
    "epscloudapi",
    "epsimaging",
    "epslabels",
    "datasets>=3.4.1",
    "huggingface-hub>=0.29.3",
    "natsort>=8.4.0",
    "nibabel>=5.3.2",
    "numpy>=1.26.4",
    "pandas>=2.2.3",
    "pillow>=11.1.0",
    "scikit-learn>=1.6.1",
    "SimpleITK>=2.4.1",
    "torch==2.5.1",
    "tqdm>=4.67.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/epsdatasets"]

[tool.uv.sources]
epscloudapi = { workspace = true }
epsimaging = { workspace = true }
epslabels = { workspace = true }
